/*! fxCanvas v0.2(beta3) (20101224)
	- copyright 2009-2010, Evgeny Burzak <http://code.google.com/p/fxcanvas/>
	- released under the MIT License <http://www.opensource.org/licenses/mit-license.php>
*/
$Package("buz.util",function(k){k.capitalize=function(l){return l.substr(0,1).toUpperCase()+l.substr(1)};var i=$Import({},"platform");k.propertyChangeListener=function(l,f,p){var q=function(c){c.attrName==f&&p(c)};if(i.platform.webkit){var a=l[f],b;setInterval(function(){b=l[f];if(a!=b){q({target:l,attrName:f,prevValue:a,newValue:b});a=b}},10+Math.round(Math.random()*100))}else l.addEventListener("DOMAttrModified",q,false)}});$Unit(__PATH__,__FILE__,function(k){k.Import("platform");$Package("buz.fxcanvas.config",function(i){k.Event.once("initialize",function(){i.version="0.2(beta3)";i.enable=true;i.tracePathBounds=k.platform.isIE;i.idleInterval=2E3;i.frameDuration=100;i.contextMenu=[{id:"view",label:{ru:"\u041e\u0442\u043a\u0440\u044b\u0442\u044c \u0438\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435",en:"View Image"}},{id:"save_as",label:{ru:"\u0421\u043e\u0445\u0440\u0430\u043d\u0438\u0442\u044c \u0438\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435 \u043a\u0430\u043a...",
en:"Save Image As..."}},"----",{id:"about",label:{ru:"\u041e \u043f\u0440\u043e\u0433\u0440\u0430\u043c\u043c\u0435 fxCanvas...",en:"About fxCanvas..."}},{id:"about_flash",label:{ru:"\u041e \u043f\u0440\u043e\u0433\u0440\u0430\u043c\u043c\u0435 Adobe Flash Player...",en:"About Adobe Flash Player..."}}];i.viewImageURL="view.php";i.saveAsURL="save.php";i.flashBackendJS="flash_backend.js";i.canvasBackendJS="canvas_backend.js";i.projectURL="http://code.google.com/p/fxcanvas/";i.fxcanvas_js="fxcanvas.js";i.script_url=
function(){for(var l=document.getElementsByTagName("script"),f=0;f<l.length;f++)if(l[f].src.indexOf(i.fxcanvas_js)>-1)return l[f].getAttribute("src",2)}();i.script_path=i.script_url.replace(/[^\/]+$/,"");i.imageProxy=i.script_path+"proxy.php";i.useCanvasPath=false;i.useRawImageData=false})})});$Unit(__PATH__,__FILE__,function(k){k.Import("buz.fxcanvas.config","platform","w3c.DOMException");$Package("buz.fxcanvas",function(i){i.throwException=function(f){throw new k.DOMException(f);};i.throwError=function(f){throw Error(f);};i.defProp={globalAlpha:1,globalCompositeOperation:"source-over",strokeStyle:"rgb(0,0,0)",fillStyle:"rgb(0,0,0)",shadowOffsetX:0,shadowOffsetY:0,shadowBlur:0,shadowColor:"rgba(0,0,0,.5)",lineWidth:1,lineCap:"butt",lineJoin:"miter",miterLimit:10,font:"10px sans-serif",
textAlign:"start",textBaseline:"alphabetic"};var l=0;i.getCanvasUUID=function(){return"canvas-uuid-"+l++};i.getCanvasParams=function(f){var p=f.getAttribute("width"),q=f.getAttribute("height"),a=f.getAttribute("oncanvasframe"),b=f.getAttribute("oncanvasresize"),c=f.getAttribute("onload"),d=f.getAttribute("tracePathBounds"),e=f.getAttribute("frameDuration");if(d){d=d.replace(/\s+/,"");switch(d){case "true":case "yes":case "1":d=true;break;case "false":case "no":case "0":d=false;break;default:d=null;
break}}return{width:p&&Number(p),height:q&&Number(q),id:f.getAttribute("id"),frameDuration:e&&parseInt(e),tracePathBounds:d,oncanvasframe:a&&Function(a),oncanvasresize:b&&Function(b),onload:c&&Function(c),offsetLeft:f.offsetLeft,offsetTop:f.offsetTop}};k.Event.once("initialize",function(){k.config.enable&&i.backend.initialize()});i.initialize=function(){i.backend.initialize()};i.initElement=function(f){i.backend.initElement(f)}})});$Unit(__PATH__,__FILE__,function(k,i,l){$Import(k,"platform","geom.*","buz.fxcanvas.config");k.Matrix2d.prototype._transform=function(){};k.Matrix2d.prototype._setTransform=function(){};k.Matrix2d.prototype._dump=function(){return[this[0],this[1],this[2],this[3],this[4],this[5]].join(",")};$Package("buz.fxcanvas",function(f){function p(a,b,c,d){this.set(a,b,c,d);this.knots=0}function q(){l.detachEvent("onbeforeunload",q);l.extCanvasRenderingContext2D=null;l.ImageData=null;l.CanvasPath=null}f.extCanvasRenderingContext2D=
function(a,b){this._isFlashBackend=k.platform.isIE;this._backend=b;this._bounds=new p;this._xy0=new k.Point;this._tracePathBounds=k.config.tracePathBounds;this._stateStack=[];this._pathStack=[];this._useRawImageData=k.config.useRawImageData;this._useCanvasPath=k.config.useCanvasPath;this.canvas=a;this.transformMatrix=new k.Matrix2d;this.transformMatrix.identity();if(!this._isFlashBackend)for(var c in f.defProp){this.__defineSetter__(c,function(d){return function(e){this._backend[d]=e}}(c));this.__defineGetter__(c,
function(d){return function(){return this._backend[d]}}(c))}};f.extCanvasRenderingContext2D.prototype={canvas:null,clearRect:function(a,b,c,d){if(arguments.length==1){b=a.y;c=a.width;d=a.height;a=a.x}this._backend.clearRect(a,b,c,d);return this},fillRect:function(a,b,c,d){if(arguments.length==1){b=a.y;c=a.width;d=a.height;a=a.x}this._backend.fillRect(a,b,c,d);return this},strokeRect:function(a,b,c,d){if(arguments.length==1){b=a.y;c=a.width;d=a.height;a=a.x}this._backend.strokeRect(a,b,c,d);return this},
closePath:function(){this._path&&this._path.close();this._backend.closePath();return this},beginPath:function(){if(this._useCanvasPath)this._path=this.createPath();if(this._tracePathBounds){this._bounds.clear();this._xy0.set(0,0)}this._backend.beginPath();return this},moveTo:function(a,b){if(arguments.length==1){b=a.y;a=a.x}this._path&&this._path.moveTo(a,b);if(this._tracePathBounds){this._xy0.set(a,b);this._bounds.addKnot(a,b)}this._backend.moveTo(a,b);return this},lineTo:function(a,b){if(arguments.length==
1){b=a.y;a=a.x}this._path&&this._path.lineTo(a,b);if(this._tracePathBounds){this._xy0.set(a,b);this._bounds.addKnot(a,b)}this._backend.lineTo(a,b);return this},arcTo:function(a,b,c,d,e){this._path&&this._path.arcTo(a,b,c,d,e);if(this._tracePathBounds){this._bounds.addKnot(a,b);this._xy0.set(a,b)}this._backend.arcTo(a,b,c,d,e)},vectorTo:function(a,b,c){if(arguments.length==1){b=a.y;a=a.x}c||(c=10);this._path&&this._path.vectorTo(a,b,c);this._backend.lineTo(a,b);var d=this._xy0.vectorTo(a,b);d=Math.atan2(d.y,
d.x);var e,h;e=c*Math.cos(d+2.61);h=c*Math.sin(d+2.61);this._backend.lineTo(a+e,b+h);e=c*Math.cos(d-2.61);h=c*Math.sin(d-2.61);this._backend.lineTo(a+e,b+h);this._backend.lineTo(a,b);return this},__drawTestPoint:function(a,b,c){this.fillStyle="grey";this.fillRect(a-2.5,b-2.5,5,5);this.fillStyle="#fff";c&&this.fillText(c,a+5,b+5)},quadraticCurveTo:function(a,b,c,d){this._path&&this._path.quadraticCurveTo(a,b,c,d);if(this._tracePathBounds){var e=this._xy0.vectorTo(c,d);e=(new k.Point(c+e.x/2,d+e.y/
2)).vectorTo(a,b);this._bounds.addKnot(c+e.x/2,d+e.y/2);this._bounds.addKnot(c,d);this._xy0.set(c,d)}this._backend.quadraticCurveTo(a,b,c,d);return this},bezierCurveTo:function(a,b,c,d,e,h){this._path&&this._path.bezierCurveTo(a,b,c,d,e,h);if(this._tracePathBounds){var j=k.Point,g=this._xy0,m=new j(e,h),n=g.vectorTo(a,b),o=m.vectorTo(c,d),r=g.vectorTo(e,h),s=new j(g.x+n.x/2,g.y+n.y/2),t=new j(e+o.x/2,h+o.y/2);o=new j(e+n.x/2+o.x/2-r.x/2,h+n.y/2+o.y/2-r.y/2);n=s.vectorTo(o);r=t.vectorTo(o);o=new j(s.x+
n.x/2,s.y+n.y/2);r=new j(t.x+r.x/2,t.y+r.y/2);n=r.vectorTo(o.x,o.y);n=new j(r.x+n.x/2,r.y+n.y/2);s=g.vectorTo(s);m=m.vectorTo(t);g=new j(g.x+s.x/2,g.y+s.y/2);m=new j(e+m.x/2,h+m.y/2);t=g.vectorTo(o);s=m.vectorTo(r);g=new j(g.x+t.x/2,g.y+t.y/2);j=new j(m.x+s.x/2,m.y+s.y/2);this._bounds.addKnot(n.x,n.y);this._bounds.addKnot(g.x,g.y);this._bounds.addKnot(j.x,j.y);this._bounds.addKnot(e,h);this._xy0.set(e,h)}this._backend.bezierCurveTo(a,b,c,d,e,h);return this},rect:function(a,b,c,d){if(arguments.length==
1){b=a.y;c=a.width;d=a.height;a=a.x}this._path&&this._path.rect(a,b,c,d);if(this._tracePathBounds){this._bounds.expandBox(a,b,c,d);this._xy0.set(a+c,b+d)}this._backend.rect(a,b,c,d);return this},arc:function(a,b,c,d,e,h){this._path&&this._path.arc(a,b,c,d,e,h);if(this._tracePathBounds){var j=c*2;this._bounds.expandBox(a-c,b-c,j,j);this._xy0.set(a+j,b+j)}this._backend.arc(a,b,c,d,e,h);return this},stroke:function(){this._path&&this._path.length&&this._backend.appendPath(this._path);this._backend.stroke();
return this},fill:function(){this._backend.fill();return this},clip:function(){this._backend.clip();return this},createPath:function(a){return new f.CanvasPath(a)},appendPath:function(a){this._path&&this._path.append(a);return this},clonePath:function(){if(this._path)return this._path.clone()},save:function(){this._path&&this._pathStack.push(this._path.clone());this._stateStack.push(this.transformMatrix.clone());this._backend.save();return this},restore:function(){this._backend.restore();this.globalAlpha=
this._backend.globalAlpha;this.globalCompositeOperation=this._backend.globalCompositeOperation;this.strokeStyle=this._backend.strokeStyle;this.fillStyle=this._backend.fillStyle;this.lineWidth=this._backend.lineWidth;this.lineCap=this._backend.lineCap;this.lineJoin=this._backend.lineJoin;this.miterLimit=this._backend.miterLimit;this.shadowOffsetX=this._backend.shadowOffsetX;this.shadowOffsetY=this._backend.shadowOffsetY;this.shadowBlur=this._backend.shadowBlur;this.shadowColor=this._backend.shadowColor;
this.font=this._backend.font;this.textAlign=this._backend.textAlign;this.textBaseline=this._backend.textBaseline;if(this._stateStack.length>0)this.transformMatrix=this._stateStack.pop();if(this._pathStack.length>0)this._path=this._pathStack.pop();return this},translate:function(a,b){this._tracePathBounds&&this.transformMatrix.translate(a,b);this._backend.translate(a,b);return this},rotate:function(a){this._tracePathBounds&&this.transformMatrix.rotate(a);this._backend.rotate(a);return this},scale:function(a,
b){this._tracePathBounds&&this.transformMatrix.scale(a,b);this._backend.scale(a,b);return this},transform:function(a,b,c,d,e,h){this._tracePathBounds&&this.transformMatrix._transform(arguments);this._backend.transform(a,b,c,d,e,h);return this},setTransform:function(a,b,c,d,e,h){this._tracePathBounds&&this.transformMatrix._setTransform(arguments);this._backend.setTransform(a,b,c,d,e,h);return this},drawImage:function(a,b,c,d,e,h,j,g,m){if(arguments.length===3)this._backend.drawImage(a,b,c);else if(arguments.length===
5)this._backend.drawImage(a,b,c,d,e);else arguments.length===9&&this._backend.drawImage(a,b,c,d,e,h,j,g,m);return this},createImageData:function(a,b){return a&&b?new f.ImageData(a,b,null,this._useRawImageData):new f.ImageData(a,null,null,this._useRawImageData)},getImageData:function(a,b,c,d){if(arguments.length==1){b=a.y;c=a.width;d=a.height;a=a.x}if(this._isFlashBackend)return null;var e=this._backend.getImageData(a,b,c,d);return this._useRawImageData?new f.ImageData(c,d,e):(new f.ImageData(1,1)).__fromCanvasData(e)},
putImageData:function(a,b,c,d,e,h,j){f.assertImageDataIsValid(a);var g;g=this._isFlashBackend?a:this._useRawImageData?a:a.__toCanvasData(this._backend);if(arguments.length==3)this._backend.putImageData(g,b,c);else arguments.length==7&&this._backend.putImageData(g,b,c,d,e,h,j)},createLinearGradient:function(a,b,c,d){return this._backend.createLinearGradient(a,b,c,d)},createRadialGradient:function(a,b,c,d,e,h){return this._backend.createRadialGradient(a,b,c,d,e,h)},createPattern:function(a,b){b||(b=
null);return this._backend.createPattern(a,b)},fillText:function(a,b,c,d){this._backend.fillText(a,b,c,d||null);return this},strokeText:function(a,b,c,d){this._backend.strokeText(a,b,c,d||null);return this},measureText:function(a){return this._backend.measureText(a)},isPointInPath:function(a,b){if(arguments.length==1){b=a.y;a=a.x}if(this._isFlashBackend)return this._tracePathBounds?this.isPointInPathBounds(a,b):false;else{if(k.platform.isFirefox){this._backend.save();this._backend.setTransform(1,
0,0,1,0,0);var c=this._backend.isPointInPath(a,b);this._backend.restore();return c}return this._backend.isPointInPath(a,b)}},isPointInPathBounds:function(a,b){if(arguments.length==1){b=a.y;a=a.x}var c=this._bounds,d=this.transformMatrix.matrix,e={x:a,y:b};d[0]==1&&d[1]==0&&d[2]==0&&d[3]==1&&d[4]==0&&d[5]==0||(e=this.transformMatrix.clone().invert().multiplyPoint(e));return c.isPointWithin(e)},ifPointInPath:function(a,b,c){c(this.isPointInPath(a,b));return this},getPathBounds:function(){return this._bounds.clone()},
set:function(a,b){this[a]=b;return this},globalAlpha:f.defProp.globalAlpha,globalCompositeOperation:f.defProp.globalCompositeOperation,strokeStyle:f.defProp.strokeStyle,fillStyle:f.defProp.fillStyle,shadowOffsetX:f.defProp.shadowOffsetX,shadowOffsetY:f.defProp.shadowOffsetY,shadowBlur:f.defProp.shadowBlur,shadowColor:f.defProp.shadowColor,lineWidth:f.defProp.lineWidth,lineCap:f.defProp.lineCap,lineJoin:f.defProp.lineJoin,miterLimit:f.defProp.miterLimit,font:f.defProp.font,textAlign:f.defProp.textAlign,
textBaseline:f.defProp.textBaseline,setGlobalAlpha:function(a){this.globalAlpha=a;return this},setGlobalCompositeOperation:function(a){this.globalCompositeOperation=a;return this},setStrokeStyle:function(a){this.strokeStyle=a;return this},setFillStyle:function(a){this.fillStyle=a;return this},setShadowOffsetX:function(a){this.shadowOffsetX=a;return this},setShadowOffsetY:function(a){this.shadowOffsetY=a;return this},setShadowBlur:function(a){this.shadowBlur=a;return this},setShadowColor:function(a){this.shadowColor=
a;return this},setLineWidth:function(a){this.lineWidth=a;return this},setLineCap:function(a){this.lineCap=a;return this},setLineJoin:function(a){this.lineJoin=a;return this},setMiterLimit:function(a){this.miterLimit=a;return this},setFont:function(a){this.font=a;return this},setTextAlign:function(a){this.textAlign=a;return this},setTextBaseline:function(a){this.textBaseline=a;return this},invoke:function(){this._backend._invoke(arguments)},dummy:function(){this._backend.dummy()},__rgbaStyle:function(a,
b,c,d){return["rgba(",[a,b,c,d].join(","),")"].join("")},__rgbStyle:function(a,b,c){return["rgb(",[a,b,c].join(","),")"].join("")},setFillStyleRGBA:function(a,b,c,d){this.fillStyle=this.__rgbaStyle(a,b,c,d);return this},setStrokeStyleRGBA:function(a,b,c,d){this.strokeStyle=this.__rgbaStyle(a,b,c,d);return this},setFillStyleRGB:function(a,b,c){this.fillStyle=this.__rgbStyle(a,b,c);return this},setStrokeStyleRGB:function(a,b,c){this.strokeStyle=this.__rgbStyle(a,b,c);return this},clear:function(){this.clearRect(0,
0,this.canvas.width,this.canvas.height);return this},constructor:f.extCanvasRenderingContext2D};p.prototype=new k.Rectangle;k.object.extend(p.prototype,{addKnot:function(a,b){var c=(new k.Point(this.x,this.y)).vectorTo(a,b);if(this.knots){if(c.x<0){this.x+=c.x;this.width-=c.x}else if(this.x+c.x>this.x+this.width)this.width=c.x;if(c.y<0){this.y+=c.y;this.height-=c.y}else if(this.y+c.y>this.y+this.height)this.height=c.y}else{this.x=a;this.y=b;this.height=this.width=0}this.knots++},clear:function(){this.knots=
this.x=this.y=this.width=this.height=0},expandBox:function(a,b,c,d){this.addKnot(a,b);this.addKnot(a+c,b+d)},clone:function(){return new p(this.x,this.y,this.width,this.height)}});f.ImageData=function(a,b,c,d){this.__useCache=false;this.__pixel=d&&k.platform.isIE?1:4;this.__cachedData=null;if(a&&b){this.width=a;this.height=b;if(c){this.data=c;return this}}else{a||f.throwException("NOT_SUPPORTED_ERR");f.assertImageDataIsValid(a);this.width=a.width;this.height=a.height}this.data=k.VectorArray(this.width*
this.height,k.Uint,32);for(a=0;a<this.height;a++)for(b=0;b<this.width;b++)this.data[a*this.width+b]=0};f.ImageData.prototype={data:null,__toCanvasData:function(a){if(this.__useCache&&this.__cachedData)return this.__cachedData;a=k.platform.isOpera?{width:this.width,height:this.height,data:Array(this.width*this.height*4)}:a.createImageData(this.width,this.height);for(var b,c,d=0;d<this.height;d++)for(var e=0;e<this.width;e++){c=d*4*this.width+e*4;b=this.data[d*this.width+e];a.data[c]=b>>24&255;a.data[c+
1]=b>>16&255;a.data[c+2]=b>>8&255;a.data[c+3]=b&255}if(this.__useCache)this.__cachedData=a;return a},__fromCanvasData:function(a){this.width=a.width;this.height=a.height;this.data=k.VectorArray(this.width*this.height,k.Uint,32);for(var b,c,d,e,h=0;h<this.height;h++)for(var j=0;j<this.width;j++){b=h*4*this.width+j*4;c=a.data[b];d=a.data[b+1];e=a.data[b+2];b=a.data[b+3];this.data[h*this.width+j]=(c<<24)+(d<<16)+(e<<8)+b}return this},__destroy:function(){this.width=this.height=this.data=null},toString:function(){return"ImageData["+
this.data.length+"]"},clone:function(){var a=new f.ImageData(this.width,this.height);a.data.set(this.data);return a}};f.assertImageDataIsValid=function(a){a.width&&isFinite(a.width)&&a.height&&isFinite(a.height)&&a.data&&a.data.length||f.throwException("TYPE_MISMATCH_ERR")};f.CanvasPath=function(){this.length=0;this._stack=[];this._serial=[];this._ie=k.platform.ie};f.CanvasPath.prototype={__copy:function(a,b){for(var c,d,e,h,j=0;j<a._stack.length;j++){c=a._stack[j][0];e=a._stack[j][1];d=e.length;
h=[];for(var g=0;g<d;g++)h[g]=e[g];b._stack[j]=[c,h];if(this._ie)b._serial[j]=a._serial[j]}},pop:function(){this._ie&&this._serial.pop();return this._stack.pop()},push:function(a){this[a[0]].apply(this,a[1])},clone:function(){var a=new f.CanvasPath;this.__copy(this,a);a.length=this.length;return a},append:function(a){this.__copy(a,this);this.length+=a.length},moveTo:function(a,b){var c=[a,b];if(this._ie)this._serial[this.length]=["B",a,"\u0001",b].join("");this._stack[this.length]=["moveTo",c];this.length++},
lineTo:function(a,b){var c=[a,b];if(this._ie)this._serial[this.length]=["C",a,"\u0001",b].join("");this._stack[this.length]=["lineTo",c];this.length++},arcTo:function(a,b,c,d,e){a=[a,b,c,d,e];if(this._ie)this._serial[this.length]=["G",a.join("\u0001")].join("");this._stack[this.length]=["arcTo",a];this.length++},vectorTo:function(a,b,c){a=[a,b,c];if(this._ie)this._serial[this.length]=["B",a.join("\u0001")].join("");this._stack[this.length]=["vectorTo",a];this.length++},bezierCurveTo:function(a,b,
c,d,e,h){a=[a,b,c,d,e,h];if(this._ie)this._serial[this.length]=["E",a.join("\u0001")].join("");this._stack[this.length]=["bezierCurveTo",a];this.length++},quadraticCurveTo:function(a,b,c,d){a=[a,b,c,d];if(this._ie)this._serial[this.length]=["D",a.join("\u0001")].join("");this._stack[this.length]=["quadraticCurveTo",a];this.length++},arc:function(a,b,c,d,e,h){a=[a,b,c,d,e,h];if(this._ie)this._serial[this.length]=["F",a.join("\u0001")].join("");this._stack[this.length]=["arc",a];this.length++},rect:function(a,
b,c,d){a=[a,b,c,d];if(this._ie)this._serial[this.length]=["H",a.join("\u0001")].join("");this._stack[this.length]=["rect",a];this.length++},close:function(){if(this._ie)this._serial[this.length]="K";this._stack[this.length]=["close"];this.length++},toSVGString:function(){},toString:function(a){if(this._ie){if(a==undefined)a="\u0001";return[this._serial.join(a),a].join("")}return"CanvasPath[]"}};f.CanvasEvent={FRAME:"1",RESIZE:"2"};if(!l.extCanvasRenderingContext2D)l.extCanvasRenderingContext2D=f.extCanvasRenderingContext2D;
if(!l.ImageData)l.ImageData=f.ImageData;if(!l.CanvasPath)l.CanvasPath=f.CanvasPath;l.attachEvent&&l.attachEvent("onbeforeunload",q)})});$Unit(__PATH__,__FILE__,function(k,i){$Import(k,"platform");$Package("buz.fxcanvas",function(l){function f(d,e){var h=this.menuEl=i.createElement("CanvasContextMenu");this.config=d;this.handlers=e;var j=0;this.selectedElement=null;this.elements=[];for(var g,m=0;m<d.length;m++){g=d[m];if(typeof g=="string"&&g.match(/[\-]+/)){g=i.createElement("hr");j+=13}else{var n=e[g.id],o=g.label[p]||g.label[q]||"<entry>";g=i.createElement("CanvasContextMenuEntry");g.onmouseenter=function(){this.contextMenu.selectedElement=
this;this.style.background=b.highlight;this.style.color=b.highlightText};g.onmouseleave=function(){this.contextMenu.selectedElement=null;this.style.background=b.background;this.style.color=b.menuText};g.style.background=b.background;g.innerHTML=g.label=o;g.contextMenu=this;g.entryHandler=n;j+=a?20:18}h.appendChild(g);this.elements.push(g)}h.style.height=j+"px"}if(k.platform.isIE){var p=navigator.browserLanguage,q="en",a=k.platform.ie<=6||i.documentMode<7||"",b={background:"Menu",menuText:"MenuText",
greyText:"GreyText",border:"ButtonShadow",highlight:"Highlight",highlightText:"HighlightText",font:"normal 8pt Tahoma, Arial"},c=["CanvasContextMenu{margin:0px;padding:2px;background-color:",b.background,";border:1px solid ",b.border,";position:absolute;top:0px;left:0px;zIndex:999;float:none;overflow:visible;display:block;clear:both;color:",b.menuText,";font:",b.font,";height:1px;",a&&"width:0;","}CanvasContextMenuEntry{text-align:left;margin:0px;padding:2px 5px 0px 24px;color:",b.menuText,";white-space:nowrap;cursor:default;float:none;display:block;overflow:visible;border:0;background-color:",
b.background,";height:",a?19:16,"px;font:",b.font,";",a&&"float:left;clear:left;width:0","}",a&&"CanvasContextMenu hr{","float:left;clear:left;padding:0;margin:3px 0px 0px 0px;height:0px}"].join("");i.createStyleSheet().cssText=c;f.prototype={hide:function(){},show:function(d,e){var h=this;if(!h.selectedElement){var j=function(){i.detachEvent("onmousedown",j);var n=h.selectedElement;if(n){n.entryHandler&&n.entryHandler();n.style.background=b.background;n.style.color=b.menuText;h.selectedElement=null}try{i.body.removeChild(h.menuEl)}catch(o){}};
this.menuEl.style.top=e+"px";this.menuEl.style.left=d+"px";i.body.appendChild(this.menuEl);if(a){for(var g=[],m=0;m<this.elements.length;m++)g.push(this.elements[m].offsetWidth);g.sort();maxWidth=g.pop();for(m=0;m<this.elements.length;m++){g=this.elements[m];g.style.minWidth=g.style.width=maxWidth-(g.tagName==="HR"?0:29)+"px"}this.menuEl.style.width=maxWidth+"px"}i.attachEvent("onmousedown",j)}}};l.ContextMenu=f}})});
