/*! fxCanvas v0.2(beta2) (20101206)
	- copyright 2009-2010, Evgeny Burzak <http://code.google.com/p/fxcanvas/>
	- released under the MIT License <http://www.opensource.org/licenses/mit-license.php>
*/
$Package("buz.util",function(g){g.updateObject=function(n,l){for(var p in l)if(!(p in Object.prototype))if(p!="__w3c_fake"&&p!="toString"&&p!="valueOf")n[p]=l[p]};g.capitalize=function(n){return n.substr(0,1).toUpperCase()+n.substr(1)};var e=$Import({},"browser");g.propertyChangeListener=function(n,l,p){var a=function(d){d.attrName==l&&p(d)};if(e.browser.webkit){var b=n[l],c;setInterval(function(){c=n[l];if(b!=c){a({target:n,attrName:l,prevValue:b,newValue:c});b=c}},10+Math.round(Math.random()*100))}else n.addEventListener("DOMAttrModified",
a,false)}});$Unit(__PATH__,__FILE__,function(g){$Import(g,"browser");$Package("buz.fxcanvas.config",function(e){e.version="0.2(beta2)";e.enable=true;e.tracePathBounds=g.browser.isIE;e.idleInterval=2E3;e.frameDuration=100;e.contextMenu=[{id:"view",label:{ru:"\u041e\u0442\u043a\u0440\u044b\u0442\u044c \u0438\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435",en:"View Image"}},{id:"save_as",label:{ru:"\u0421\u043e\u0445\u0440\u0430\u043d\u0438\u0442\u044c \u0438\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435 \u043a\u0430\u043a...",
en:"Save Image As..."}},"----",{id:"about",label:{ru:"\u041e \u043f\u0440\u043e\u0433\u0440\u0430\u043c\u043c\u0435 fxCanvas...",en:"About fxCanvas..."}},{id:"about_flash",label:{ru:"\u041e \u043f\u0440\u043e\u0433\u0440\u0430\u043c\u043c\u0435 Adobe Flash Player...",en:"About Adobe Flash Player..."}}];e.viewImageURL="view.php";e.saveAsURL="save.php";e.flashBackendJS="$(flashBackendJS)";e.canvasBackendJS="$(canvasBackendJS)";e.projectURL="http://code.google.com/p/fxcanvas/";e.script_url=function(){var n=document.getElementsByTagName("script"),
l=n[n.length-1];if(l.getAttribute("src")=="//0")l=n[n.length-2];return l.getAttribute("src",2)}();e.script_path=e.script_url.replace(/[^\/]+$/,"");e.imageProxy=e.script_path+"proxy.php"})});$Unit(__PATH__,__FILE__,function(g){$Import(g,"buz.fxcanvas.config","browser");$Package("buz.fxcanvas",function(e){e.throwException=function(l){throw new e._DOMException(l);};e.throwError=function(l){throw Error(l);};e._DOMException=DOMException;e.defProp={globalAlpha:1,globalCompositeOperation:"source-over",strokeStyle:"rgb(0,0,0)",fillStyle:"rgb(0,0,0)",shadowOffsetX:0,shadowOffsetY:0,shadowBlur:0,shadowColor:"rgba(0,0,0,.5)",lineWidth:1,lineCap:"butt",lineJoin:"miter",miterLimit:10,font:"10px sans-serif",
textAlign:"start",textBaseline:"alphabetic"};var n=0;e.getCanvasUUID=function(){return"canvas-uuid-"+n++};e.getCanvasParams=function(l){var p=l.getAttribute("width"),a=l.getAttribute("height"),b=l.getAttribute("oncanvasframe"),c=l.getAttribute("onload"),d=l.getAttribute("tracePathBounds"),f=l.getAttribute("frameDuration");if(d){d=d.replace(/\s+/,"");switch(d){case "true":case "yes":case "1":d=true;break;case "false":case "no":case "0":d=false;break;default:d=null;break}}return{width:p&&Number(p),
height:a&&Number(a),id:l.getAttribute("id"),frameDuration:f&&parseInt(f),tracePathBounds:d,onframe:b&&Function(b),onload:c&&Function(c),offsetLeft:l.offsetLeft,offsetTop:l.offsetTop}};addDOMLoadEvent(function(){g.config.enable&&e.backend.initialize()});e.initialize=function(){e.backend.initialize()};e.initElement=function(l){e.backend.initElement(l)}})});$Unit(__PATH__,__FILE__,function(g){$Import(g,"browser","geom.*","buz.fxcanvas.config");$Package("buz.fxcanvas",function(e){function n(a,b,c,d){g.Rectangle.call(this,a||0,b||0,c||0,d||0);this.y0=this.x0=0}function l(){window.detachEvent("onbeforeunload",l);window.extCanvasRenderingContext2D=null;window.ImageData=null;window.CanvasPath=null}var p=Array.prototype.slice;e.extCanvasRenderingContext2D=function(a,b){this._isFlashBackend=g.browser.isIE;this._backend=b;this._bounds=new n;this._tracePathBounds=
g.config.tracePathBounds;this._stateStack=[];this._pathStack=[];this._useRawImageData=false;this.canvas=a;g.Matrix.prototype._transform=function(){};g.Matrix.prototype._setTransform=function(d){this.a=d[0];this.c=d[1];this.b=d[2];this.d=d[3];this.tx=d[4];this.ty=d[5]};g.Matrix.prototype._dump=function(){return[this.a,this.b,this.c,this.d,this.tx,this.ty].join(",")};this.transformMatrix=new g.Matrix;if(!this._isFlashBackend)for(var c in e.defProp){this.__defineSetter__(c,function(d){return function(f){this._backend[d]=
f}}(c));this.__defineGetter__(c,function(d){return function(){return this._backend[d]}}(c))}};e.extCanvasRenderingContext2D.prototype={canvas:null,clearRect:function(a,b,c,d){var f;if(arguments.length==1){f=a.x;b=a.y;c=a.width;d=a.height}else f=a;this._backend.clearRect(f,b,c,d);return this},fillRect:function(a,b,c,d){var f;if(arguments.length==1){f=a.x;b=a.y;c=a.width;d=a.height}else f=a;this._backend.fillRect(f,b,c,d);return this},strokeRect:function(a,b,c,d){var f;if(arguments.length==1){f=a.x;
b=a.y;c=a.width;d=a.height}else f=a;this._backend.strokeRect(f,b,c,d);return this},closePath:function(){this._backend.closePath();return this},beginPath:function(){this._path=this.createPath();this._tracePathBounds&&this._bounds.clear();this._backend.beginPath();return this},moveTo:function(a,b){this._tracePathBounds&&this._bounds.addKnot(a,b);this._backend.moveTo(a,b);return this},lineTo:function(a,b){this._tracePathBounds&&this._bounds.addKnot(a,b);this._backend.lineTo(a,b);return this},arcTo:function(a,
b,c,d,f){this._tracePathBounds&&this._bounds.addKnot(a,b);this._backend.arcTo(a,b,c,d,f)},vectorTo:function(a,b){this._backend.lineTo(a,b);return this},__drawTestPoint:function(a,b,c){this.fillStyle="#f00";this.fillRect(a-2.5,b-2.5,5,5);this.fillStyle="#fff";c&&this.fillText(c,a+5,b+5)},quadraticCurveTo:function(a,b,c,d){if(this._tracePathBounds){var f=(new g.Point(this._bounds.x0,this._bounds.y0)).vectorTo(c,d);f=(new g.Point(c+f.x/2,d+f.y/2)).vectorTo(a,b);this._bounds.addKnot(c+f.x/2,d+f.y/2);
this._bounds.addKnot(c,d)}this._backend.quadraticCurveTo(a,b,c,d);return this},bezierCurveTo:function(a,b,c,d,f,i){if(this._tracePathBounds){var j=(new g.Point(this._bounds.x0,this._bounds.y0)).vectorTo(a,b),k=(new g.Point(f,i)).vectorTo(c,d),h=(new g.Point(this._bounds.x0,this._bounds.y0)).vectorTo(f,i),m=new g.Point(this._bounds.x0+j.x/2,this._bounds.y0+j.y/2),o=new g.Point(f+k.x/2,i+k.y/2);k=new g.Point(f+j.x/2+k.x/2-h.x/2,i+j.y/2+k.y/2-h.y/2);j=(new g.Point(m.x,m.y)).vectorTo(k.x,k.y);h=(new g.Point(o.x,
o.y)).vectorTo(k.x,k.y);k=new g.Point(m.x+j.x/2,m.y+j.y/2);h=new g.Point(o.x+h.x/2,o.y+h.y/2);j=(new g.Point(h.x,h.y)).vectorTo(k.x,k.y);j=new g.Point(h.x+j.x/2,h.y+j.y/2);m=(new g.Point(this._bounds.x0,this._bounds.y0)).vectorTo(m.x,m.y);var q=(new g.Point(f,i)).vectorTo(o.x,o.y);o=new g.Point(this._bounds.x0+m.x/2,this._bounds.y0+m.y/2);m=new g.Point(f+q.x/2,i+q.y/2);k=(new g.Point(o.x,o.y)).vectorTo(k.x,k.y);h=(new g.Point(m.x,m.y)).vectorTo(h.x,h.y);o=new g.Point(o.x+k.x/2,o.y+k.y/2);m=new g.Point(m.x+
h.x/2,m.y+h.y/2);this._bounds.addKnot(j.x,j.y);this._bounds.addKnot(o.x,o.y);this._bounds.addKnot(m.x,m.y);this._bounds.addKnot(f,i)}this._backend.bezierCurveTo(a,b,c,d,f,i);return this},rect:function(a,b,c,d){var f;if(arguments.length==1){f=a.x;b=a.y;c=a.width;d=a.height}else f=a;this._tracePathBounds&&this._bounds.expandBox(f,b,c,d);this._backend.rect(f,b,c,d);return this},arc:function(a,b,c,d,f,i){this._tracePathBounds&&this._bounds.expandBox(a-c,b-c,c*2,c*2);this._backend.arc(a,b,c,d,f,i);return this},
stroke:function(){this._path.length&&this._backend.appendPath(this._path);this._backend.stroke();return this},fill:function(){this._backend.fill();return this},clip:function(){this._backend.clip();return this},createPath:function(a){return new e.CanvasPath(a)},appendPath:function(a){this._path.append(a);return this},clonePath:function(){return this._path.clone()},save:function(){this._path&&this._pathStack.push(this._path.clone());this._stateStack.push(this.transformMatrix.clone());this._backend.save();
return this},restore:function(){this._backend.restore();this.globalAlpha=this._backend.globalAlpha;this.globalCompositeOperation=this._backend.globalCompositeOperation;this.strokeStyle=this._backend.strokeStyle;this.fillStyle=this._backend.fillStyle;this.lineWidth=this._backend.lineWidth;this.lineCap=this._backend.lineCap;this.lineJoin=this._backend.lineJoin;this.miterLimit=this._backend.miterLimit;this.shadowOffsetX=this._backend.shadowOffsetX;this.shadowOffsetY=this._backend.shadowOffsetY;this.shadowBlur=
this._backend.shadowBlur;this.shadowColor=this._backend.shadowColor;this.font=this._backend.font;this.textAlign=this._backend.textAlign;this.textBaseline=this._backend.textBaseline;if(this._stateStack.length>0)this.transformMatrix=this._stateStack.pop();if(this._pathStack.length>0)this._path=this._pathStack.pop();return this},translate:function(a,b){this._tracePathBounds&&this.transformMatrix.translate(a,b);this._backend.translate(a,b);return this},rotate:function(a){this._tracePathBounds&&this.transformMatrix.rotate(a);
this._backend.rotate(a);return this},scale:function(a,b){this._tracePathBounds&&this.transformMatrix.scale(a,b);this._backend.scale(a,b);return this},transform:function(a,b,c,d,f,i){this._tracePathBounds&&this.transformMatrix._transform(arguments);this._backend.transform(a,b,c,d,f,i);return this},setTransform:function(a,b,c,d,f,i){this._tracePathBounds&&this.transformMatrix._setTransform(arguments);this._backend.setTransform(a,b,c,d,f,i);return this},drawImage:function(a,b,c,d,f,i,j,k,h){if(arguments.length===
3)this._backend.drawImage(a,b,c);else if(arguments.length===5)this._backend.drawImage(a,b,c,d,f);else arguments.length===9&&this._backend.drawImage(a,b,c,d,f,i,j,k,h);return this},createImageData:function(a,b){return a&&b?new e.ImageData(a,b,null,this._useRawImageData):new e.ImageData(a,null,null,this._useRawImageData)},getImageData:function(a,b,c,d){if(arguments.length==1){b=a.y;c=a.width;d=a.height;a=a.x}if(this._isFlashBackend)return null;var f=this._backend.getImageData(a,b,c,d);return this._useRawImageData?
new e.ImageData(c,d,f):(new e.ImageData(1,1)).__fromCanvasData(f)},putImageData:function(a,b,c,d,f,i,j){e.assertImageDataIsValid(a);var k;k=this._isFlashBackend?a:this._useRawImageData?a:a.__toCanvasData(this._backend);if(arguments.length==3)this._backend.putImageData(k,b,c);else arguments.length==7&&this._backend.putImageData(k,b,c,d,f,i,j)},createLinearGradient:function(a,b,c,d){return this._backend.createLinearGradient(a,b,c,d)},createRadialGradient:function(a,b,c,d,f,i){return this._backend.createRadialGradient(a,
b,c,d,f,i)},createPattern:function(a,b){b||(b=null);return this._backend.createPattern(a,b)},fillText:function(a,b,c,d){this._backend.fillText(a,b,c,d||null);return this},strokeText:function(a,b,c,d){this._backend.strokeText(a,b,c,d||null);return this},measureText:function(a){return this._backend.measureText(a)},isPointInPath:function(a,b){if(this._isFlashBackend)return this._tracePathBounds?this.isPointInPathBounds(a,b):false;else{if(g.browser.isFirefox){this._backend.save();this._backend.setTransform(1,
0,0,1,0,0);var c=this._backend.isPointInPath(a,b);this._backend.restore();return c}return this._backend.isPointInPath(a,b)}},isPointInPathBounds:function(a,b){var c=this.getPathBounds(),d=new g.Point(a,b);this.transformMatrix.multiplyPoint(d);if(d.x>c.x&&d.y>c.y&&d.x<c.x+c.width&&d.y<c.y+c.height)return true;return false},ifPointInPath:function(a,b,c){c(this.isPointInPath(a,b));return this},getPathBounds:function(){return this._bounds.clone()},set:function(a,b){this[a]=b;return this},globalAlpha:e.defProp.globalAlpha,
globalCompositeOperation:e.defProp.globalCompositeOperation,strokeStyle:e.defProp.strokeStyle,fillStyle:e.defProp.fillStyle,shadowOffsetX:e.defProp.shadowOffsetX,shadowOffsetY:e.defProp.shadowOffsetY,shadowBlur:e.defProp.shadowBlur,shadowColor:e.defProp.shadowColor,lineWidth:e.defProp.lineWidth,lineCap:e.defProp.lineCap,lineJoin:e.defProp.lineJoin,miterLimit:e.defProp.miterLimit,font:e.defProp.font,textAlign:e.defProp.textAlign,textBaseline:e.defProp.textBaseline,setGlobalAlpha:function(a){this.globalAlpha=
a;return this},setGlobalCompositeOperation:function(a){this.globalCompositeOperation=a;return this},setStrokeStyle:function(a){this.strokeStyle=a;return this},setFillStyle:function(a){this.fillStyle=a;return this},setShadowOffsetX:function(a){this.shadowOffsetX=a;return this},setShadowOffsetY:function(a){this.shadowOffsetY=a;return this},setShadowBlur:function(a){this.shadowBlur=a;return this},setShadowColor:function(a){this.shadowColor=a;return this},setLineWidth:function(a){this.lineWidth=a;return this},
setLineCap:function(a){this.lineCap=a;return this},setLineJoin:function(a){this.lineJoin=a;return this},setMiterLimit:function(a){this.miterLimit=a;return this},setFont:function(a){this.font=a;return this},setTextAlign:function(a){this.textAlign=a;return this},setTextBaseline:function(a){this.textBaseline=a;return this},invoke:function(){this._backend._invoke(arguments)},dummy:function(){this._backend.dummy()},__rgbaStyle:function(){return["rgba(",p.call(arguments,0).join(","),")"].join("")},__rgbStyle:function(){return["rgb(",
p.call(arguments,0).join(","),")"].join("")},setFillStyleRGBA:function(a,b,c,d){this.fillStyle=this.__rgbaStyle(a,b,c,d);return this},setStrokeStyleRGBA:function(a,b,c,d){this.strokeStyle=this.__rgbaStyle(a,b,c,d);return this},setFillStyleRGB:function(a,b,c){this.fillStyle=this.__rgbStyle(a,b,c);return this},setStrokeStyleRGB:function(a,b,c){this.strokeStyle=this.__rgbStyle(a,b,c);return this},clear:function(){this.clearRect(0,0,this.canvas.width,this.canvas.height);return this},constructor:e.extCanvasRenderingContext2D};
n.prototype={__set:g.Rectangle.prototype.__set,isPointWithin:g.Rectangle.prototype.isPointWithin,addKnot:function(a,b){var c=(new g.Point(this.x,this.y)).vectorTo(a,b);if(this.x==0)this.x=a;else if(c.x<0||this.x==0){this.x+=c.x;this.width-=c.x}else if(this.x+c.x>this.x+this.width)this.width=c.x;if(this.y==0)this.y=b;else if(c.y<0){this.y+=c.y;this.height-=c.y}else if(this.y+c.y>this.y+this.height)this.height=c.y;this.x0=a;this.y0=b},clear:function(){this.x0=this.y0=this.x=this.y=this.width=this.height=
0},expandBox:function(a,b,c,d){this.addKnot(a,b);this.addKnot(a+c,b+d)},clone:function(){return new n(this.x,this.y,this.width,this.height)}};e.ImageData=function(a,b,c,d){this.__useCache=false;this.__pixel=d&&!g.browser.ie?4:1;this.__cachedData=null;if(a&&b){this.width=a;this.height=b;if(c){this.data=c;return this}}else{a||e.throwException("NOT_SUPPORTED_ERR");e.assertImageDataIsValid(a);this.width=a.width;this.height=a.height}this.data=Array(this.width*this.height);for(a=0;a<this.height;a++)for(b=
0;b<this.width;b++)this.data[a*this.width+b]=0};e.ImageData.prototype={data:null,__setPixel:function(){},__getPixel:function(){},__toCanvasData:function(a){if(this.__useCache&&this.__cachedData)return this.__cachedData;a=g.browser.isOpera?{width:this.width,height:this.height,data:Array(this.width*this.height*4)}:a.createImageData(this.width,this.height);for(var b,c,d=0;d<this.height;d++)for(var f=0;f<this.width;f++){c=d*4*this.width+f*4;b=this.data[d*this.width+f];a.data[c]=b>>24&255;a.data[c+1]=
b>>16&255;a.data[c+2]=b>>8&255;a.data[c+3]=b&255}if(this.__useCache)this.__cachedData=a;return a},__fromCanvasData:function(a){this.width=a.width;this.height=a.height;this.data=Array(this.width*this.height);for(var b,c,d,f,i=0;i<this.height;i++)for(var j=0;j<this.width;j++){b=i*4*this.width+j*4;c=a.data[b];d=a.data[b+1];f=a.data[b+2];b=a.data[b+3];this.data[i*this.width+j]=(c<<24)+(d<<16)+(f<<8)+b}return this},__destroy:function(){this.width=this.height=this.data=null},toString:function(){return"ImageData["+
this.data.length+"]"}};e.assertImageDataIsValid=function(a){a.width&&isFinite(a.width)&&a.height&&isFinite(a.height)&&a.data&&a.data.length||e.throwException("TYPE_MISMATCH_ERR")};e.CanvasPath=function(){this.length=0;this._stack=[];this._serial=[];this._ie=g.browser.ie};e.CanvasPath.prototype={__copy:function(a,b){for(var c,d,f,i,j=0;j<a._stack.length;j++){c=a._stack[j][0];f=a._stack[j][1];d=f.length;i=[];for(var k=0;k<d;k++)i[k]=f[k];b._stack[j]=[c,i];if(this._ie)b._serial[j]=a._serial[j]}},pop:function(){this._ie&&
this._serial.pop();return this._stack.pop()},push:function(a){this[a[0]].apply(this,a[1])},clone:function(){var a=new e.CanvasPath;this.__copy(this,a);a.length=this.length;return a},append:function(a){this.__copy(a,this);this.length+=a.length},moveTo:function(a,b){var c=[a,b];if(this._ie)this._serial[this.length]=["B",a,"\u0001",b].join("");this._stack[this.length]=["moveTo",c];this.length++},lineTo:function(a,b){var c=[a,b];if(this._ie)this._serial[this.length]=["C",a,"\u0001",b].join("");this._stack[this.length]=
["lineTo",c];this.length++},arcTo:function(a,b,c,d,f){a=[a,b,c,d,f];if(this._ie)this._serial[this.length]=["G",a.join("\u0001")].join("");this._stack[this.length]=["arcTo",a];this.length++},vectorTo:function(a,b){var c=[a,b];if(this._ie)this._serial[this.length]=["B",a,"\u0001",b].join("");this._stack[this.length]=["vectorTo",c];this.length++},bezierCurveTo:function(a,b,c,d,f,i){a=[a,b,c,d,f,i];if(this._ie)this._serial[this.length]=["E",a.join("\u0001")].join("");this._stack[this.length]=["bezierCurveTo",
a];this.length++},quadraticCurveTo:function(a,b,c,d){a=[a,b,c,d];if(this._ie)this._serial[this.length]=["D",a.join("\u0001")].join("");this._stack[this.length]=["quadraticCurveTo",a];this.length++},arc:function(a,b,c,d,f,i){a=[a,b,c,d,f,i];if(this._ie)this._serial[this.length]=["F",a.join("\u0001")].join("");this._stack[this.length]=["arc",a];this.length++},rect:function(a,b,c,d){a=[a,b,c,d];if(this._ie)this._serial[this.length]=["H",a.join("\u0001")].join("");this._stack[this.length]=["rect",a];
this.length++},close:function(){if(this._ie)this._serial[this.length]="K";this._stack[this.length]=["close"];this.length++},toSVGString:function(){},toString:function(a){if(this._ie){if(a==undefined)a="\u0001";return[this._serial.join(a),a].join("")}return"CanvasPath[]"}};e.CanvasEvent={FRAME:"1",RESIZE:"2"};if(!window.extCanvasRenderingContext2D)window.extCanvasRenderingContext2D=e.extCanvasRenderingContext2D;if(!window.ImageData)window.ImageData=e.ImageData;if(!window.CanvasPath)window.CanvasPath=
e.CanvasPath;window.attachEvent&&window.attachEvent("onbeforeunload",l)})});$Unit(__PATH__,__FILE__,function(g,e){$Import(g,"browser");$Package("buz.fxcanvas",function(n){function l(f,i){var j=this.menuEl=e.createElement("CanvasContextMenu");this.config=f;this.handlers=i;var k=0;this.selectedElement=null;this.elements=[];for(var h,m=0;m<f.length;m++){h=f[m];if(typeof h=="string"&&h.match(/[\-]+/)){h=e.createElement("hr");k+=13}else{var o=i[h.id],q=h.label[p]||h.label[a]||"<entry>";h=e.createElement("CanvasContextMenuEntry");h.onmouseenter=function(){this.contextMenu.selectedElement=
this;this.style.background=c.highlight;this.style.color=c.highlightText};h.onmouseleave=function(){this.contextMenu.selectedElement=null;this.style.background=c.background;this.style.color=c.menuText};h.style.background=c.background;h.innerHTML=h.label=q;h.contextMenu=this;h.entryHandler=o;k+=b?20:18}j.appendChild(h);this.elements.push(h)}j.style.height=k+"px"}if(g.browser.isIE){var p=navigator.browserLanguage,a="en",b=g.browser.ie<=6||e.documentMode<7||"",c={background:"Menu",menuText:"MenuText",
greyText:"GreyText",border:"ButtonShadow",highlight:"Highlight",highlightText:"HighlightText",font:"normal 8pt Tahoma, Arial"},d=["CanvasContextMenu{margin:0px;padding:2px;background-color:",c.background,";border:1px solid ",c.border,";position:absolute;top:0px;left:0px;zIndex:999;float:none;overflow:visible;display:block;clear:both;color:",c.menuText,";font:",c.font,";height:1px;",b&&"width:0;","}CanvasContextMenuEntry{text-align:left;margin:0px;padding:2px 5px 0px 24px;color:",c.menuText,";white-space:nowrap;cursor:default;float:none;display:block;overflow:visible;border:0;background-color:",
c.background,";height:",b?19:16,"px;font:",c.font,";",b&&"float:left;clear:left;width:0","}",b&&"CanvasContextMenu hr{","float:left;clear:left;padding:0;margin:3px 0px 0px 0px;height:0px}"].join("");e.createStyleSheet().cssText=d;l.prototype={hide:function(){},show:function(f,i){var j=this;if(!j.selectedElement){var k=function(){e.detachEvent("onmousedown",k);var o=j.selectedElement;if(o){o.entryHandler&&o.entryHandler();o.style.background=c.background;o.style.color=c.menuText;j.selectedElement=null}try{e.body.removeChild(j.menuEl)}catch(q){}};
this.menuEl.style.top=i+"px";this.menuEl.style.left=f+"px";e.body.appendChild(this.menuEl);if(b){for(var h=[],m=0;m<this.elements.length;m++)h.push(this.elements[m].offsetWidth);h.sort();maxWidth=h.pop();for(m=0;m<this.elements.length;m++){h=this.elements[m];h.style.minWidth=h.style.width=maxWidth-(h.tagName==="HR"?0:29)+"px"}this.menuEl.style.width=maxWidth+"px"}e.attachEvent("onmousedown",k)}}};n.ContextMenu=l}})});
