/*! JooScript basics v0.1(beta2) (20110122)
	- copyright 2009-2011, Evgeny Burzak <http://burzak.com/proj/jooscript-basics>
	- released under the MIT License <http://www.opensource.org/licenses/mit-license.php>
*/
__FILE__=__PATH__=__FUNC__=__CLASS__=__GROUP__=__LINE__="";
(function(){if(typeof $jooscript=="undefined"){(function(){function f(){function o(){return o.caller===f}return!o.apply(null,[])}var k=f(),h=Function.prototype;if(k){h.__native__apply=h.apply;h.__native__call=h.call;h.apply=function o(x,v){this.__caller__=o.caller;return this.__native__apply(x,v)};h.call=function o(){this.__caller__=o.caller;return this.__native__call.__native__apply(this,arguments)}}h["new"]=function(){var o={};o.__proto__=this.prototype;var x=this.apply(o,arguments);return x!==
null&&typeof x==="object"?x:o}})();(function(){var f=typeof window;$globals=(f=!(f=="undefined"||f=="object"&&window==null))?window:this;var k=!!$globals.navigator;$root=$globals.document?document:{};$isCLI=!k;$isWorker=!$isCLI&&!f})();addDOMLoadEvent=function(){function f(){f.done=true;for(clearInterval(h);x=k.shift();)x();if(o)o.onreadystatechange=""}var k=[],h,o,x,v;$globals.__init__=f;return function(y){if(f.done)return y();if(!k[0]){!$root.__w3c_fake&&$root.addEventListener&&$root.addEventListener("DOMContentLoaded",
f,false);eval("/*@cc_on @*/");eval('/*@if(@_win32)document.write("<script id=__ie_onload defer src=//0></scr"+"ipt>");script=document.getElementById("__ie_onload");script.onreadystatechange=function(){if(this.readyState=="complete")__init__();};document.onreadystatechange=function(){if(document.readyState=="complete"){__init__();document.onreadystatechange=null;}}@*//*@end@*/');if(!$isCLI&&!$isWorker)if(/WebKit/i.test(navigator.userAgent))h=setInterval(function(){/loaded|complete/.test(document.readyState)&&
f()},10);v=$globals.onload;$globals.onload=function(){f();v&&v()}}k.push(y)}}();var ea=function(){function f(){if(f.caller===f)return this;var b=new f;b.useCapture=false;b.__class__=f;var c=f.prototype.__new__,g=f.prototype.when,r=f.prototype.dispatch,p=f.prototype.remove;c(b);b.when=function(w,u,i){return g(b,w,u,i,false)};b.once=function(w,u,i){return g(b,w,u,i,true)};b.dispatch=function(w,u){return r(b,w,u)};b.remove=function(w,u){return p(b,w,u)};return b}function k(b){b=(typeof b=="string"?b:
b.type).toLowerCase();if(b==x)return v;return b}function h(b,c){for(var g,r,p=0;p<c.length;p++)if(g=c[p])if(g.type==b){var w;try{r=g.handler.call(g.context,{})}catch(u){w=u}if(g.fireOnce)c[p]=null;if(w)throw w;if(r)break}}var o=[];f.__classId__=f.className="Event";var x="DOMContentLoaded",v="contentloaded";f.prototype={__class__:f,__new__:function(b){b.__listeners__=[]},when:function(b,c,g,r,p){var w;if(r==undefined||r==null){r=g;w=o}else w=b.__listeners__;c=k(c);c==v&&addDOMLoadEvent(function(){h(v,
w)});w.push({type:c,handler:r,context:b,fireOnce:p})},dispatch:function(b,c,g){c=k(c);h(c,g==undefined?o:b.__listeners__)},remove:function(b,c,g,r){if(r==undefined){r=g;b=o}else b=b.__listeners__;c=k(c);r=r;b=b;for(var p=0;p<b.length;p++)if(g=b[p])if(g.type==c&&g.handler===r)b[p]=null}};f["new"]=function(){return new this};var y=f();f.when=y.when;f.once=y.once;f.dispatch=y.dispatch;f.remove=y.remove;return f}(),Va=function(){var f=function(h){this.code=this[h];this.message=h+": DOM Exception "+this.code},
k=f.prototype=Error();k.INDEX_SIZE_ERR=1;k.DOMSTRING_SIZE_ERR=2;k.HIERARCHY_REQUEST_ERR=3;k.WRONG_DOCUMENT_ERR=4;k.INVALID_CHARACTER_ERR=5;k.NO_DATA_ALLOWED_ERR=6;k.NO_MODIFICATION_ALLOWED_ERR=7;k.NOT_FOUND_ERR=8;k.NOT_SUPPORTED_ERR=9;k.INUSE_ATTRIBUTE_ERR=10;k.INVALID_STATE_ERR=11;k.SYNTAX_ERR=12;k.INVALID_MODIFICATION_ERR=13;k.NAMESPACE_ERR=14;k.INVALID_ACCESS_ERR=15;k.VALIDATION_ERR=16;k.TYPE_MISMATCH_ERR=17;$globals.DOMException||($globals.DOMException=f);return f}();(function(){function f(i,
q){for(var s in q)if(!(s in Object.prototype))if(s!="__w3c_fake"&&s!="toString"&&s!="__proto__"&&s!="valueOf")i[s]=q[s]}function k(){return{type:null,target:null,relatedTarget:null,currentTarget:null,offsetParent:null,offsetTop:null,offsetLeft:null,screenX:null,screenY:null,pageX:null,pageY:null,altKey:null,shiftKey:null,ctrlKey:null,metaKey:null,button:null,mouseButton:null,charCode:null,keyCode:null,IEvent:$root.createEventObject(),preventDefault:function(){event.returnValue=false},stopPropagation:function(){event.cancelBubble=
true}}}function h(i,q,s){if(arguments.length<3)throw Error("Not enough arguments");if(typeof q!="function")throw Error("Event handler is not a function");i=""+i;s=!!s;var H="opener"in this;if(i in g)if(!(this.tagName&&this.tagName.toLowerCase()in c||this===$root||H))return;var z=k();H=H&&(i in g||i in r)?b:this;var G=this,C="__ievent_hdlr_"+(s?"capture":"nocapture"),R=function(){z.type=event.type;z.target=event.srcElement;z.relatedTarget=event.fromElement||event.toElement||null;z.currentTarget=G;
z.offsetParent=event.srcElement&&event.srcElement.parentNode||null;z.offsetTop=event.offsetX;z.offsetLeft=event.offsetY;z.screenX=event.screenX;z.screenY=event.screenY;z.pageX=event.clientX+$root.body.scrollLeft+$root.documentElement.scrollLeft;z.pageY=event.clientY+$root.body.scrollTop+$root.documentElement.scrollTop;z.altKey=event.altKey;z.shiftKey=event.shiftKey;z.ctrlKey=event.ctrlKey;z.metaKey=false;z.keyCode=event.keyCode;z.charCode=i=="keypress"?event.keyCode:0;if(event.button==1)z.button=
0;else if(event.button==2)z.button=2;else if(event.button==4)z.button=1;z.mouseButton=event.button;q.call(G,z)},U=function(){var T=event,A={type:""};A.type=i;if(i==="DOMAttrModified"){A.ADDITION=2;A.MODIFICATION=1;A.REMOVAL=3;A.target=T.srcElement;A.relatedNode=null;A.attrChange=1;A.attrName=T.propertyName.split(".")[0];A.prevValue=null;A.newValue=A.target[A.attrName];if(A.attrName=="innerHTML"||A.attrName=="innerText"||typeof A.newValue=="function")return}q.call(G,A)};q[C]=i.indexOf("DOM")===0?U:
R;if(i==="DOMContentLoaded")addDOMLoadEvent(q[C]);else i==="DOMAttrModified"?H.attachEvent("onpropertychange",q[C]):H.attachEvent("on"+i,q[C])}function o(i,q,s){s="__ievent_hdlr_"+(s?"cap":"nocap");q[s]&&this.detachEvent("on"+i,q[s])}function x(i){return this.fireEvent("on"+i.type,i.IEvent)}function v(){for(var i=arguments,q,s=0;s<i.length;s++)if(i[s]){if(typeof i[s]=="string")q=$root.getElementById(i[s]);else if(typeof i[s]=="object")q=i[s];if(!q.__w3c_fake){q.addEventListener=h;q.removeEventListener=
o;q.dispatchEvent=x;q.__w3c_fake=true}}}if(!($isCLI||$isWorker)){var y=$globals,b=$root;if(b.uniqueID&&b.expando){if(!y.__w3c_fake){var c={textarea:true,input:true,select:true,body:true},g={keydown:"keydown",keyup:"keyup",keypress:"keypress"},r={mouseenter:"mouseenter",mouseleave:"mouseleave",mousemove:"mousemove",mouseup:"mouseup",mousedown:"mousedown",click:"click"},p;$root.__native__createElement=$root.createElement;$root.createElement=function(i){if(/^[a-z]+$/i.test(i))i=i.toUpperCase();i=$root.__native__createElement(i);
var q=window,s;s=i.tagName.toLowerCase();s=s.substr(0,1).toUpperCase()+s.substr(1);i=(q=q["HTML"+s+"Element"])&&q.__IElementConstructor?q.__IElementConstructor(i):i;v(i);p.__w3c_fake&&f(i,p.prototype);q&&q.__w3c_fake&&f(i,q.prototype);return i};$root.createEvent=function(i){var q=k();if(i=="MouseEvents"||i=="MouseEvent")q.initMouseEvent=function(s,H,z,G,C,R,U,T,A,J,Z,oa,fa,pa,qa){this.type=this.IEvent.type=s;this.bubbles=H;this.cancelable=z;this.view=G;this.detail=C;this.screenX=R;this.screenY=U;
this.clientX=T;this.clientY=A;this.ctrlKey=J;this.altKey=Z;this.shiftKey=oa;this.metaKey=fa;this.button=pa;this.relatedTarget=qa};else if(i=="KeyboardEvent"||i=="KeyEvents")q.initKeyEvent=function(s,H,z,G,C,R,U,T,A,J){this.type=this.IEvent.type=s;this.bubbles=H;this.cancelable=z;this.view=G;this.ctrlKey=C;this.altKey=R;this.shiftKey=U;this.keyCode=A;this.charCode=J};else q.initEvent=function(s,H,z){this.type=this.IEvent.type=s;this.bubbles=H;this.cancelable=z};return q};b.defaultView=y;y.getComputedStyle=
function(i){return{getPropertyValue:function(q){return i.currentStyle[q]}}};v.all=function(){for(var i=b.all,q=0;q<i.length;q+=1)v(i[q])};y.w3c=v;for(var w=["HTMLElement"],u=0;u<w.length;u++)y[w[u]]||(y[w[u]]={prototype:{},__elementName:w[u],toString:function(){return"[object "+this.__elementName+"]"},__w3c_fake:true});p=y.HTMLElement}}else{y.w3c=function(){};w3c.all=w3c}}})();(function(){var f=typeof $trace_disable!="undefined"?$trace_disable:$isWorker;if(typeof console=="undefined")$globals.console=
{log:function(){for(var k=[],h=0;h<arguments.length;h++)k.push(arguments[h]);typeof alert=="undefined"?print.apply(null,k):alert(k.join(", "))},dir:function(){}};$globals.trace=!f?function(){console&&console.log(["trace: ",Array.prototype.slice.call(arguments,0).join(" ")].join(""))}:function(){}})();(function(){function f(a){a=new ra(a===undefined?"":a);a.__type__=$|D;a.__class__=f;return a}function k(a){a=new Ba(a===undefined?false:a);a.__type__=aa|D;a.__class__=k;return a}function h(a){a=F(a===
undefined?0:a);if(a==Infinity){a=new F(Infinity);a.__type__=P}else if(a==-Infinity){a=new F(-Infinity);a.__type__=P}else if(a===a){a=new F(a);a.__type__=ba}else{a=new F(NaN);a.__type__=ca}a.__type__|=D;a.__class__=h;return a}function o(a){a=F(a===undefined?0:a);if(a==Infinity){a=new F(Infinity);a.__type__=P}else if(a==-Infinity){a=new F(-Infinity);a.__type__=P}else if(a===a){a=new F(a|0);a.__type__=V}else{a=new F(NaN);a.__type__=ca}a.__type__|=D;a.__class__=o;return a}function x(a){a=F(a===undefined?
0:a);if(a==Infinity){a=new F(Infinity);a.__type__=P}else if(a==-Infinity){a=new F(-Infinity);a.__type__=P}else if(a===a){a=new F(Math.abs(a|0));a.__type__=W}else{a=new F(NaN);a.__type__=ca}a.__type__|=D;a.__class__=x;return a}function v(a){a=new F(a===undefined?0:a);a.__type__=(a==Infinity||a==-Infinity?P:a+0===a+0?E:ca)|D;a.__class__=v;return a}function y(){return null}function b(){}function c(a){throw TypeError(a);}function g(a){for(var d={},e=0;e<a.length;e++)d[a[e][0]]=a[e][1];return d}function r(){}
function p(a,d){var e=a.split(Ja);e=qa(e);d.call(e,e)}function w(a){this.__groupToken__=a}function u(a,d,e){if(e===undefined)e=Ka;for(var t in d)if(e[t]===undefined)a[t]=d[t];return a}function i(a,d,e){d||(d=a);for(var t=d.ancestors,m,n=0;n<t.length;n++){m=t[n];if(J(m))throw Error("Undefined ancestor in class "+a.className);m!=a&&m!=d&&i(a,m,e);m.classBody.call(a.prototype,a);if(m.className)a.ancestors[m.className]=m}}function q(){}function s(a,d,e,t){function m(j){return j===m?this:m["new"].apply(m,
arguments)}function n(){var j=m;i(j);j.classBody.call(j.prototype,j);C(j.__init__)===M&&j.__init__();m["new"]=z}m.prototype=new G;m.className=a;m.classBody=e||q;m.ancestors=[];m.role=N();if(d&&d.length>0)for(a=0;a<d.length;a++)if(Z(d[a])){m.ancestors[a]=d[a];m.role.inherit(d[a].role)}else c(d[a]+" is not a class");m.role.inherit(t);Ca.once("initialize",n);A(m);La&&n();return m}function H(){return"$"+Math.round(Math.random()*1E6).toString(33)}function z(){var a=arguments,d=new this(this,a),e=this.prototype;
if(!d.__proto__)d.__proto__=e;var t=null,m=0;if(this.role)for(var n in this.role)if(!(n in ga)){if(e[n]===undefined){trace(this.className,n);throw Error("ClassError: "+(this.className+" does not match the class role"));}var j=this.role[n];if(j){j={writable:j.internal===undefined?j.frozen===undefined?j["public"]===undefined?true:j["public"]:!j.frozen:!j.internal,configurable:j.internal===undefined?j.sealed===undefined?j["public"]===undefined?true:j["public"]:!j.sealed:!j.internal,enumerable:j.internal===
undefined?j.hidden===undefined?j["public"]===undefined?true:j["public"]:!j.hidden:!j.internal,type:j.type||0,constructor:typeof j.constructor==="function"?false:j.constructor,returnType:C(j.returnType)&E?j.returnType+0:0,argumentType:j.argumentType};if(!Da)if(j.writable+j.configurable+j.enumerable<3)throw Error("ClassError: browser is not ECMAScript 5 compliant. Please upgrade your browser!");var L=j.type;if(L)if((L^M)&ha)j.value=e[n];else{if(L&M){L=j;var Ma=d,sa=n,da=Na&&j.returnType||0,ia=Na&&j.argumentType||
[],S=this.__classId__+"-"+sa,Q=Ea[S],Oa=this.prototype,ta=Oa[sa];if(Q===undefined||Q.fun!==ta){Q=H();var Pa=H(),K=ta.toString().replace(/\/\*.*\*\//g,"").match(/function(\s+)?([a-zA-Z\$_0-9]+)?(\s+)?\(([a-zA-Z\$_0-9,\s]+)\)/),ua=void 0,O=void 0,I=void 0,va=void 0,ja=void 0;if(K&&K.length>1){K=K[4].replace(/\s+/g,"").split(",");ua=ka.call(K,1).join(",");O=K[0];var la=void 0;if(ia.length){la=[];for(I=0;I<ia.length;I++)if(ia[I].__type__&E)la[I]=K[I+1]+".__type__ & "+(ia[I]+0)+" ? "+K[I+1]+" : "+Q+"("+
Pa+")";else c("argument type is not a number")}else la=ua;I=K[K.length-1];if(I=="__rest__"){va="__rest__";ja=K.length-1}}else{ua="";O="self"}I=H();K=H();var wa=void 0;if(da&(xa|ya))wa=O+" === null || "+O+" === undefined ? "+O+" : ";else if(da)wa=O+".__type__ & "+da+" ? "+O+" : ";da=[ia.length?"var "+Pa+"='argument type does not match a class spec';":"","return function(",ua,") {",va?["if(arguments.length>=",ja,"){",va,"=[arguments[",ja-1,"]];for(var ",I,"=",ja,";",I,"<arguments.length;",I,"++)",va,
"[",I,"-",ja-1,"]=arguments[",I,"];}"].join(""):"",da?O+"=":"return ",K,".",sa,"(",O,la&&[",",la].join(""),")",wa?";return "+wa+Q+"('return type does not match a class spec')":"","}"].join("");Q=Ea[S]=Function(O,K,Q,da);Q.fun=ta}S=Q(Ma,Oa,c);S.__name__=sa;S.__owner__=Ma;S.__func__=ta;S.toString=U;L.value=S;if(j.constructor)if(m)throw Error("ClassError: "+(this.className+" has multiple constructors at once"));else{t=j.value;m+=1}}}else j.value=e[n];if(Da)Qa(d,n,j);else d[n]=j.value}}e=0;m=z.caller||
z.__caller__;for(n=null;m;){if(m.__owner__){n=m.__owner__;break}m=m.caller;if(e>1E3){n=null;break}e++}d.parent=n;d.__class__=this;e=null;if(C(t)&M&&t!==this&&t!==Fa)e=t.apply(d,a);return C(e)&D?e:d}function G(){}function C(a){if(a===undefined)return ya;else if(a===null)return xa;else if(a.__type__===undefined||a.__type__===null)switch(typeof a){case "number":return E;case "string":return $;case "function":return M;case "boolean":return aa;case "object":return D}else return a.__type__}function R(a){var d=
C(a);d&D||c(a+" is not an object");return Z(a.__class__)?a.__class__:d&V^E?o:d&W^E?x:d&ba^E?h:d&aa^E?k:d&E?v:d&$?f:d&M?Ga:d&ha?G:d&Ha?za:d&D?X:null}function U(){return"function wrapped(){/*stub*/}"}function T(){return["class ",this.className||"Anonymous","(...)"].join("")}function A(a,d){if(!J(a.__classId__)&&J(d))d=a.__classId__;else if(J(d))d=ma.length;if(!J(ma[d]))throw Error("A class has already registered in the roaster");var e=a.prototype;if(C(a)===M){if(!a.className){var t=a.toString().match(/function(\s+)?([a-zA-Z\$_0-9]+)?/);
a.className=t&&t[2]||null}e.__class__=a;if(J(e.__proto__))e.__proto__=e;if(!a.role)a.role=N();a.toString=T;a.__type__=ha}if(a.__classId__!=d)a.__classId__=d;ma[d]=a}function J(a){return a===undefined||a===null}function Z(a){return!J(a)&&ma[a.__classId__]===a}function oa(a,d,e){var t=Y();fa(t,"joo.*");t.__path__=a;t.__file__=d;e.call(t,t,Wa,l)}function fa(a){var d,e,t,m,n=ka.call(arguments,1);if(typeof a=="string"){n=ka.call(arguments,0);a=this}for(var j=0;j<n.length;j++){d=n[j];e=d.split(Ja);t=Xa.call(e);
e=t=="*"?ka.call(e,0,e.length-1):e;try{m=qa(e)}catch(L){throw Error(L.message+" in "+d);}if(t==="*")u(a,m,w.prototype);else a[t]=m}return a}function pa(){}function qa(a,d){var e=l[Aa],t=e,m,n;if(a.length==1&&!a[0])return t;for(n=0;n<a.length;n++){m=a[n];if(!e.__groupToken__)throw Error("Token '"+m+"' is not group token");t=e[m];if(typeof t=="undefined")if(d)throw Error("Token "+m+" not found");else t=e=e[m]=new w(m);else if(n==a.length-1)break;else{e=t;t=e[m]}}return t}function B(){if(!arguments.length)throw Error("Type is not constructor!");
}function N(a,d){if(N.caller===N)return this;var e=new N;d&&e.inherit(d);a&&e.inherit(a);return e}function Ra(a,d){for(var e in a)if(!(e in ga))if(J(d[e]))return null;return d}function Ia(a,d){if(J(a))a=0;if(J(d))d=o(32);if(typeof ArrayBuffer==="undefined"){var e=typeof a==="object"?a:Array(a);e.buffer=e;e.set=function(j){for(var L=0;L<e.buffer.length;L++)e.buffer[L]=j[L]};return e}var t=C(a)==D?a.length:a,m=new ArrayBuffer(t*d),n=C(d)^E;if(n&V&&d+0==8)n=Int8Array;else if(n&W&&d+0==8)n=Uint8Array;
else if(n&V&&d+0==16)n=Int16Array;else if(n&W&&d+0==16)n=Uint16Array;else if(n&V&&d+0==32)n=Int32Array;else if(n&W&&d+0==32)n=Uint32Array;else if(n&ba&&d+0==32)n=Float32Array;else if(n&ba&&d+0==64)n=Float64Array;else throw Error("VectorArray: syntax error");e=new n(m,0,t);C(a)==D&&e.set(a);return e}function Y(a,d){if(Y.caller===Y)return this;var e=new Y;if(arguments.length==1){d=a;d=undefined}e.prefix=a;e.uri=d;return e}function za(){ka.call(arguments,0).join("")}function Sa(){$globals.detachEvent("onbeforeunload",
Sa);Ea=ma=null;$globals[Aa]=null;na||(l.Number=l.Float=l.Int=l.Uint=l.Boolean=l.String=l.VectorArray=l.Null=l.Void=l.Role=l.Class=l.Type=l.dict=l.zip=null);l.$Unit=l.$Package=l.$Import=l.$ImportFrom=l.$Namespace=l.$buildClass=l.$Event=null;if(l.XML)l.XML=null}var l=$globals,Wa=$root,La=false,na=typeof $joo_compat!=="undefined"?$joo_compat:true,Na=typeof $use_runtime_typing!=="undefined"?$use_runtime_typing:true,D,E,V,W,ba,$,aa,M,ha,Ha,xa,ya,P,ca;D=1;E=2;P=E|128;ca=E|256;V=E|4;W=E|8;ba=E|16;aa=E|32;
$=64;M=D|512;ha=D|M|1024;Ha=D|2048;ya=4096;xa=8192;var F=Number,ra=String,Ba=Boolean,Fa=Object,Ta=Function,X=Fa,Ga=Ta;f.fromCharCode=ra.fromCharCode;v.prototype=h.prototype=o.prototype=F.prototype;f.prototype=ra.prototype;k.prototype=Ba.prototype;v["new"]=h["new"]=o["new"]=f["new"]=k["new"]=y["new"]=b["new"]=function(a){return this(a)};var Aa="$groups",Ja=".",ka=Array.prototype.slice,Xa=function(){return this[this.length-1]},Ca=ea();(function(a){this.message=a}).prototype=Error();w.prototype={__groupToken__:null};
var Ka={__proto__:null,__class__:null,__classId__:null,__type__:null},ma=[],Ea={};G.prototype={__class__:null,parent:null,toString:function(){return this.__str__?this.__str__():["[class ",this.__class__&&this.__class__.className||"Anonymous","]"].join("")}};G["new"]=z;G.registerClass=A;G.registerClasses=function(){for(var a=0;a<arguments.length;a++)A(arguments[a])};var Ua=typeof Object.getPrototypeOf==="function"?Object.getPrototypeOf:function(a){C(a)&D||c("x is not object");return typeof a.__proto__===
"object"?a.__proto__:Object.prototype},Qa=typeof Object.defineProperty==="function"?Object.defineProperty:function(){},Da=function(){try{var a={};Qa(a,"x",{value:1,writeable:false,enumerable:false,configurable:false});if(a.x===undefined)return false;a.x=2;if(a.x===2)return false;delete a.x;if(a.x===undefined)return false;for(var d in a)if(d==="x")return false;return true}catch(e){return false}}();B.lastId=0;B.getTypeId=function(){return++this.lastId<<16};N.prototype={match:function(a){C(a)&D||c(a+
" is not an object");return Ra(this,a)},inherit:function(a){u(this,a,ga)},__type__:B.getTypeId()};var ga={};u(ga,Ka,{});u(ga,N.prototype);N.match=Ra;l[Aa]={};l[Aa].__groupToken__="root";l.$Unit=oa;l.$Package=p;l.$Import=fa;l.$ImportFrom=pa;l.$Event=ea;l.$buildClass=s;if(!na)X.extend=u;if(typeof X.getPrototypeOf!=="function")X.getPrototypeOf=Ua;if(typeof X.getClassOf!=="function")X.getClassOf=R;if(!na){l.Number=v;l.Float=h;l.Int=o;l.Uint=x;l.Boolean=k;l.String=f;l.VectorArray=Ia;l.Null=y;l.Void=b;
l.Role=N;l.Class=G;l.Type=B}if(!l.XML)if(!na){l.XML=za;l.Namespace=Y}if(typeof window!="undefined")l.$window=window;if(typeof document!="undefined")l.$document=document;B.isVoid=J;B.isPrimitive=function(a){try{return Ua(a)===Object.prototype}catch(d){return false}};B.isClass=Z;B.isObject=function(a){return!!(C(a)&D)};B.is_a=function(a,d){try{return Z(d)?R(a)===d:false}catch(e){return false}};B.getTypeOf=C;B.NUMBER=E;B.INT=V;B.UINT=W;B.FLOAT=ba;B.BOOLEAN=aa;B.STRING=$;B.VOID=ya;B.NULL=xa;B.OBJECT=
D;B.FUNCTION=M;B.CLASS=ha;B.XML=Ha;B.NAN=ca;B.INFINITY=P;if(!na){Fa.prototype.__type__=D;Ta.prototype.__type__=M}ra.prototype.__type__=$;Ba.prototype.__type__=aa;F.prototype.__type__=E;p("joo",function(a){a.Number=v;a.Float=h;a.Int=o;a.Uint=x;a.Null=y;a.Void=b;a.Object=X;a.Boolean=k;a.String=f;a.VectorArray=Ia;a.Type=B;a.Role=N;a.Import=fa;a.ImportFrom=pa;a.Package=p;a.Unit=oa;a.Namespace=Y;a.Group=w;a.Function=Ga;a.Class=G;a.XML=za;a.Event=ea;a.buildClass=s});p("joo.object",function(a){a.extend=
u;a.dict=g;a.zip=r});p("platform",function(a){a.ecmascript5compliant=Da});Ca.once("contentloaded",function(){La=true;Ca.dispatch("initialize")});(function(){for(var a,d=0;d<arguments.length;d++){a=arguments[d];A(a)}})(v,o,x,h,f,k,Ga,y,b,G,Y,za,Ia,ea);$globals.attachEvent&&$globals.attachEvent("onbeforeunload",Sa)})();$Unit(__PATH__,__FILE__,function(f){f.Package("w3c",function(k){k.DOMException=Va})});$Unit(__PATH__,__FILE__,function(f,k){$Package("platform",function(h){function o(r){for(var p=0;p<
r.length;p++){var w=r[p].s,u=r[p].p;g=r[p].v||r[p].i;if(w){if(w.indexOf(r[p].u)!=-1)return r[p].i}else if(u)return r[p].i}}function x(r){var p=r.indexOf(g);if(p!=-1)return parseFloat(r.substring(p+g.length+1))}var v=!$isCLI&&navigator.appVersion,y=!$isCLI&&navigator.userAgent,b=!$isCLI&&navigator.platform,c=!$isCLI&&navigator.vendor,g;c=[{s:y,u:"Chrome",i:"Chrome"},{s:y,u:"OmniWeb",v:"OmniWeb/",i:"OmniWeb"},{s:c,u:"Apple",i:"Safari",v:"Version"},{p:$globals.opera,i:"Opera"},{s:c,u:"iCab",i:"iCab"},
{s:c,u:"KDE",i:"Konqueror"},{s:y,u:"Firefox",i:"Firefox"},{s:c,u:"Camino",i:"Camino"},{s:y,u:"Netscape",i:"Netscape"},{s:y,u:"MSIE",i:"Explorer",v:"MSIE"},{s:y,u:"Gecko",i:"Mozilla",v:"rv"},{s:y,u:"Mozilla",i:"Netscape",v:"Mozilla"}];b=[{s:b,u:"Win",i:"Windows"},{s:b,u:"Mac",i:"Mac"},{s:y,u:"iPhone",i:"iPhone/iPod"},{s:b,u:"Linux",i:"Linux"}];h.browser=$isCLI?null:o(c)||"An unknown browser";h.version=$isCLI?null:x(y)||x(v)||"an unknown version";h.OS=$isCLI?null:o(b)||"an unknown OS";h.isIE=!!(k.uniqueID&&
k.expando&&h.browser==="Explorer");h.ie=h.isIE?h.version:0;h.isFirefox=h.browser==="Firefox";h.firefox=h.isFirefox?h.version:0;h.isOpera=h.browser==="Opera";h.opera=h.isOpera?h.version:0;h.isWebKit=h.browser==="Chrome"||h.browser==="Safari";h.webkit=h.isWebKit?1:0;h.isCLI=$isCLI})});$Unit(__PATH__,__FILE__,function(f){f.Package("geom",function(k){function h(b){return["(",b.join(", "),")"].join("")}function o(b,c){if(o.caller===o)return this;var g=new o;arguments.length==2&&g.set(b,c);return g}function x(b,
c,g,r){if(x.caller===x)return this;var p=new x;arguments.length==4&&p.set(b,c,g,r);return p}function v(b,c,g,r,p,w){if(v.caller===v)return this;var u=new v;u.matrix=f.VectorArray(6,f.Float(32));if(arguments.length)if(f.Type.is_a(b,v)){c=u.matrix;g=b.matrix;c[0]=g[0];c[1]=g[1];c[2]=g[2];c[3]=g[3];c[4]=g[4];c[5]=g[5]}else if(arguments.length===6){u.matrix[0]=b;u.matrix[1]=c;u.matrix[2]=g;u.matrix[3]=r;u.matrix[4]=p;u.matrix[5]=w}else throw Error("Matrix2d: syntax error");else return u;return u}var y=
f.Event();o.className=o.__classId__="Point";o.role=f.Role(o,{x:f.Number,y:f.Number});o.prototype={vectorTo:function(b,c){if(arguments.length==1){c=b.y;b=b.x}return new o((b>this.x?1:-1)*(Math.max(this.x,b)-Math.min(this.x,b)),(c>this.y?1:-1)*(Math.max(this.y,c)-Math.min(this.y,c)))},set:function(b,c){this.x=b;this.y=c;return this},toString:function(){return h([this.x,this.y])},clone:function(){return o(this.x,this.y)}};x.className=x.__classId__="Rectangle";x.role=f.Role(x,{width:f.Number,height:f.Number},
o.role);x.prototype={set:function(b,c,g,r){this.x=b;this.y=c;this.width=g;this.height=r;return this},isPointWithin:function(b,c){if(arguments.length==1){c=b.y;b=b.x}return b>this.x&&c>this.y&&b<this.x+this.width&&c<this.y+this.height},clone:function(){return x(this.x,this.y,this.width,this.height)},toString:function(){return h([this.x,this.y,this.width,this.height])}};v.prototype={identity:function(){this.matrix[0]=1;this.matrix[1]=0;this.matrix[2]=0;this.matrix[3]=1;this.matrix[4]=0;this.matrix[5]=
0;return this},translate:function(b,c){var g=this.matrix;g[4]=g[0]*b+g[2]*c;g[5]=g[1]*b+g[3]*c;return this},scale:function(b,c){var g=this.matrix;g[0]*=b;g[2]*=b;g[1]*=c;g[3]*=c;return this},rotate:function(b){var c=this.matrix,g=Math.cos(b);b=Math.sin(b);var r=c[2]*g+c[3]*b,p=c[0]*-b+c[1]*g,w=c[2]*-b+c[3]*g;c[0]=c[0]*g+c[1]*b;c[1]=r;c[2]=p;c[3]=w;return this},multiplyPoint:function(b){var c=this.matrix,g=b.x;b=b.y;return new o(g*c[0]+b*c[2]+c[4],g*c[1]+b*c[3]+c[5])},multiplyMatrix:function(b){var c=
this.matrix;b=b.matrix;var g=c[1]*b[0]+c[3]*b[1],r=c[0]*b[2]+c[2]*b[3],p=c[1]*b[2]+c[3]*b[3],w=c[0]*b[4]+c[2]*b[5]+c[4],u=c[1]*b[4]+c[3]*b[5]+c[5];c[0]=c[0]*b[0]+c[2]*b[1];c[1]=g;c[2]=r;c[3]=p;c[4]=w;c[5]=u;return this},invert:function(){var b=this.matrix,c=1/(b[0]*b[3]-b[1]*b[2]);this.matrix.set([b[3]*c,-b[1]*c,-b[2]*c,b[0]*c,c*(b[2]*b[5]-b[3]*b[4]),c*(b[1]*b[4]-b[0]*b[5])]);return this},clone:function(){return v(this)},toString:function(){var b=this.matrix;return h([b[0],b[1],b[2],b[3],b[4],b[5]])}};
v.className=v.__classId__="Matrix2d";k.Point=o;k.Rectangle=x;k.Matrix2d=v;y.once("initialize",function(){f.Class.registerClasses(o,x,v)})})});if($isCLI||$isWorker){__init__.done=true;ea.dispatch("contentloaded")}}})();$jooscript="(dev)";
