/*! JooScript basics v0.03 (20101106)
	- copyright 2009-2010, Evgeny Burzak <http://burzak.com/proj/jooscript>
	- released under the MIT License <http://www.opensource.org/licenses/mit-license.php>
*/
var __PUBLIC__=0,__PRIVATE__=1,__STATIC__=2,__GLOBAL__=4,__FINAL__=8,__PROTECTED__=16,__FROZEN__=32,__INTERNAL__=49;__FILE__=__PATH__=__FUNC__=__CLASS__=__GROUP__=__LINE__="";
addDOMLoadEvent=function(){var r=[],l,i,w,y,b=function(){i=true;for(clearInterval(l);w=r.shift();)w()};window.__init__=b;return function(a){if(i)return a();if(!r[0]){!document.__w3c_fake&&document.addEventListener&&document.addEventListener("DOMContentLoaded",b,false);eval("/*@cc_on @*/");eval('/*@if(@_win32)document.write("<script id=__ie_onload defer src=//0></scr"+"ipt>");script=document.getElementById("__ie_onload");script.onreadystatechange=function(){if(this.readyState=="complete")__init__();};document.onreadystatechange=function(){if(document.readyState=="complete"){__init__();document.onreadystatechange=null;}}@*//*@end@*/');if(/WebKit/i.test(navigator.userAgent))l=
setInterval(function(){/loaded|complete/.test(document.readyState)&&b()},10);y=window.onload;window.onload=function(){b();y&&y()}}r.push(a)}}();
(function(){function r(){var a=this;this.useCapture=false;this.__class__=r;this.__id__=r.instances.length;r.instances.push(this);var d=r.members.__new__.__func__,j=r.members.when.__func__,n=r.members.dispatch.__func__,o=r.members.remove.__func__;d(a);this.when=function(u,A,D,h){return j(a,u,A,D,h)};this.dispatch=function(u,A){return n(a,u,A)};this.remove=function(u,A){return o(a,u,A)}}function l(a){a=(typeof a=="string"?a:a.type).toLowerCase();if(a==y)return b;return a}function i(a,d){for(var j,n,
o=0;o<d.length;o++)if(j=d[o])if(j.type==a){n=j.handler.call(j.context,{});if(j.fireOnce)d[o]=null;if(n)break}}var w=[];r.className="Event";r.instances=[];var y="DOMContentLoaded",b="contentloaded";r.members={__new__:{__func__:function(a){a.__listeners__=[]}},when:{__func__:function(a,d,j,n,o){var u;if(n==undefined||n==null){n=j;u=w}else u=a.__listeners__;evtype=l(d);evtype==b&&addDOMLoadEvent(function(){i(b,u)});u.push({type:evtype,handler:n,context:a,fireOnce:o})}},dispatch:{__func__:function(a,
d,j){d=l(d);i(d,j==undefined?w:a.__listeners__)}},remove:{__func__:function(a,d,j,n){if(n==undefined){n=j;a=w}else a=a.__listeners__;d=l(d);n=n;a=a;for(var o=0;o<a.length;o++)if(j=a[o])if(j.type==d&&j.handler===n)a[o]=null}}};r["new"]=function(){return new this};window.$Event=r})();
(function(){if(document.uniqueID&&document.expando){var r=function(i){this.code=this[i];this.message=i+": DOM Exception "+this.code},l=r.prototype=Error();l.INDEX_SIZE_ERR=1;l.DOMSTRING_SIZE_ERR=2;l.HIERARCHY_REQUEST_ERR=3;l.WRONG_DOCUMENT_ERR=4;l.INVALID_CHARACTER_ERR=5;l.NO_DATA_ALLOWED_ERR=6;l.NO_MODIFICATION_ALLOWED_ERR=7;l.NOT_FOUND_ERR=8;l.NOT_SUPPORTED_ERR=9;l.INUSE_ATTRIBUTE_ERR=10;l.INVALID_STATE_ERR=11;l.SYNTAX_ERR=12;l.INVALID_MODIFICATION_ERR=13;l.NAMESPACE_ERR=14;l.INVALID_ACCESS_ERR=
15;l.VALIDATION_ERR=16;l.TYPE_MISMATCH_ERR=17;window.DOMException||(window.DOMException=r)}})();
(function(){function r(h,m){for(var k in m)if(!(k in Object.prototype))if(k!="__w3c_fake"&&k!="toString"&&k!="__proto__"&&k!="valueOf")h[k]=m[k]}function l(){return{type:null,target:null,relatedTarget:null,currentTarget:null,offsetParent:null,offsetTop:null,offsetLeft:null,screenX:null,screenY:null,pageX:null,pageY:null,altKey:null,shiftKey:null,ctrlKey:null,metaKey:null,button:null,mouseButton:null,charCode:null,keyCode:null,IEvent:document.createEventObject(),preventDefault:function(){event.returnValue=
false},stopPropagation:function(){event.cancelBubble=true}}}function i(h,m,k){if(arguments.length<3)throw Error("Not enough arguments");if(typeof m!="function")throw Error("Event handler is not a function");h=""+h;k=!!k;var B="opener"in this;if(h in n)if(!(this.tagName&&this.tagName.toLowerCase()in j||this===document||B))return;var t=l();B=B&&(h in n||h in o)?d:this;var F=this,v="__ievent_hdlr_"+(k?"capture":"nocapture"),K=function(){var s=event;t.type=s.type;t.target=s.srcElement;t.relatedTarget=
s.fromElement||s.toElement||null;t.currentTarget=F;t.offsetParent=s.srcElement&&s.srcElement.parentNode||null;t.offsetTop=s.offsetX;t.offsetLeft=s.offsetY;t.screenX=s.screenX;t.screenY=s.screenY;t.pageX=s.clientX+d.body.scrollLeft+d.documentElement.scrollLeft;t.pageY=s.clientY+d.body.scrollTop+d.documentElement.scrollTop;t.altKey=s.altKey;t.shiftKey=s.shiftKey;t.ctrlKey=s.ctrlKey;t.metaKey=false;t.keyCode=s.keyCode;t.charCode=h=="keypress"?s.keyCode:0;if(s.button==1)t.button=0;else if(s.button==2)t.button=
2;else if(s.button==4)t.button=1;t.mouseButton=s.button;m.call(F,t)},H=function(){var s=event,x={type:""};x.type=h;if(h==="DOMAttrModified"){x.ADDITION=2;x.MODIFICATION=1;x.REMOVAL=3;x.target=s.srcElement;x.relatedNode=null;x.attrChange=1;x.attrName=s.propertyName.split(".")[0];x.prevValue=null;x.newValue=x.target[x.attrName];if(x.attrName=="innerHTML"||x.attrName=="innerText"||typeof x.newValue=="function")return}m.call(F,x)};m[v]=h.indexOf("DOM")===0?H:K;if(h==="DOMContentLoaded")addDOMLoadEvent(m[v]);
else h==="DOMAttrModified"?B.attachEvent("onpropertychange",m[v]):B.attachEvent("on"+h,m[v])}function w(h,m,k){k="__ievent_hdlr_"+(k?"cap":"nocap");m[k]&&this.detachEvent("on"+h,m[k])}function y(h){return this.fireEvent("on"+h.type,h.IEvent)}function b(){for(var h=arguments,m,k=0;k<h.length;k++)if(h[k]){if(typeof h[k]=="string")m=document.getElementById(h[k]);else if(typeof h[k]=="object")m=h[k];if(!m.__w3c_fake){m.addEventListener=i;m.removeEventListener=w;m.dispatchEvent=y;m.__w3c_fake=true}}}var a=
window,d=a.document;if(d.uniqueID&&d.expando){if(!a.__w3c_fake){document.createElement("canvas");document.createStyleSheet().cssText="canvas{display:inline-block;overflow:hidden;width:300px;height:150px}";var j={textarea:true,input:true,select:true,body:true},n={keydown:"keydown",keyup:"keyup",keypress:"keypress"},o={mouseenter:"mouseenter",mouseleave:"mouseleave",mousemove:"mousemove",mouseup:"mouseup",mousedown:"mousedown",click:"click"},u;document.__native__createElement=document.createElement;
document.createElement=function(h){if(/^[a-z]+$/i.test(h))h=h.toUpperCase();h=document.__native__createElement(h);var m=window,k;k=h.tagName.toLowerCase();k=k.substr(0,1).toUpperCase()+k.substr(1);h=(m=m["HTML"+k+"Element"])&&m.__IElementConstructor?m.__IElementConstructor(h):h;b(h);u.__w3c_fake&&r(h,u.prototype);m&&m.__w3c_fake&&r(h,m.prototype);return h};document.createEvent=function(h){var m=l();if(h=="MouseEvents"||h=="MouseEvent")m.initMouseEvent=function(k,B,t,F,v,K,H,s,x,I,M,P,J,L,N){this.type=
this.IEvent.type=k;this.bubbles=B;this.cancelable=t;this.view=F;this.detail=v;this.screenX=K;this.screenY=H;this.clientX=s;this.clientY=x;this.ctrlKey=I;this.altKey=M;this.shiftKey=P;this.metaKey=J;this.button=L;this.relatedTarget=N};else if(h=="KeyboardEvent"||h=="KeyEvents")m.initKeyEvent=function(k,B,t,F,v,K,H,s,x,I){this.type=this.IEvent.type=k;this.bubbles=B;this.cancelable=t;this.view=F;this.ctrlKey=v;this.altKey=K;this.shiftKey=H;this.keyCode=x;this.charCode=I};else m.initEvent=function(k,
B,t){this.type=this.IEvent.type=k;this.bubbles=B;this.cancelable=t};return m};d.defaultView=a;a.getComputedStyle=function(h){return{getPropertyValue:function(m){return h.currentStyle[m]}}};b.all=function(){for(var h=d.all,m=0;m<h.length;m+=1)b(h[m])};a.w3c=b;for(var A=["HTMLElement"],D=0;D<A.length;D++)a[A[D]]||(a[A[D]]={prototype:{},__elementName:A[D],toString:function(){return"[object "+this.__elementName+"]"},__w3c_fake:true});u=a.HTMLElement}}else{a.w3c=function(){};w3c.all=w3c}})();
(function(){if(typeof console=="undefined")window.console={log:function(){for(var r=[],l=0;l<arguments.length;l++)r.push(arguments[l]);typeof alert=="undefined"?print.apply(null,r):alert(r.join(", "))},dir:function(){}};window.trace=function(){console&&console.log(["trace: ",Array.prototype.slice.call(arguments,0).join(" ")].join(""))}})();
(function(){function r(c){this.message=c}function l(c,f){var g=c.split(Z);g=D(g);f.call(g,g)}function i(c){this[S]=c}function w(c){var f=c.__class__||c,g,e,q;if(f!=c)g=c;y(f);f.body.call(f.members,f);for(var p in f.members)if(!(p in n.prototype)){e=f.members[p];q=e.type;if(c===f){if(!(e.flags&T))continue}else if(e.flags&T)continue;if(q===J)if(e.flags&T)c[p]=e.__func__;else{c[p]=e(c,p);c[p].__name__=p;c[p].__owner__=c;c[p].__func__=e.__func__;c[p].toString=e.toString}else c[p]=q===L?e:q===I?e.valueOf():
q===s||q===x?e.valueOf():q===M?e.valueOf():q===N?null:e}g||f.__init__()}function y(c,f,g){f||(f=c);for(var e=f.ancestors,q=0;q<e.length;q++){if(e[q]==undefined)throw Error("Undefined ancestor in class "+c.className);e[q]!=c&&e[q]!=f&&y(c,e[q],g);e[q].body.call(c.members,c);if(e[q].className)c.ancestors[e[q].className]=e[q]}}function b(){}function a(c,f,g){this.instances=[];this.className=c;this.ancestors=[];if(f&&f.length>0)for(c=0;c<f.length;c++)this.ancestors[c]=f[c];this.body=g;this.members=new n;
var e=this;U.when("initialize",function(){w(e)},null,true);$[$.length]=this}function d(c){switch(typeof c){case "string":return I;case "function":return c instanceof a?L:J;case "boolean":return M;case "object":return P;case "number":return c.toString().indexOf(".")>-1?x:s;default:return N}}function j(){return"function(){/*stub*/}"}function n(){}function o(c,f,g){var e=new h;e.__path__=c;e.__file__=f;g.call(e,e,K,v)}function u(c){var f,g,e,q,p=Q.call(arguments,1);if(typeof c=="string")c=v;for(var z=
0;z<p.length;z+=1){f=p[z];g=f.split(Z);e=ba.call(g);g=e=="*"?Q.call(g,0,g.length-1):g;try{q=D(g)}catch(C){throw new r("Symbol "+C+" not found in "+f);}if(e==="*"){f=c;e=q;for(var E in e)if(!(E in Object.prototype)&&!(E in Function.prototype)&&!(E in Class.prototype)&&E!=S)f[E]=e[E]}else c[e]=q}return c}function A(){}function D(c,f){var g=t[V],e=g,q,p;if(c.length==1&&!c[0])return e;for(p=0;p<c.length;p++){q=c[p];if(!g[S])throw"Token '"+q+"' is not group token";e=g[q];if(typeof e=="undefined")if(f)throw q+
" not found";else e=g=g[q]=new i(q);else if(p==c.length-1)break;else{g=e;e=g[q]}}return e}function h(c){return{__url__:c}}function m(){Q.call(arguments,0).join("")}function k(){}function B(){window.detachEvent("onbeforeunload",B)}var t=window,F=document,v=t,K=F,H=false,s=0,x=1,I=2,M=3,P=4,J=5,L=6,N=8,T=__STATIC__,W=function(c){c=new Number(c);c.typeId=x;return c},X=function(c){c=new Number(c);c.typeId=s;return c},Y=function(){return null},aa=function(){},V="$groups",S="__groupToken__",Z=".",Q=Array.prototype.slice,
ba=function(){return this[this.length-1]},U=$Event["new"]();r.prototype=Error();i.prototype={addClass:function(c,f){this[f.className]=f}};var $=[];if(window.Touch){var O=Function.prototype;O.__native__apply=O.apply;O.__native__call=O.call;O.apply=function c(f,g){this.__caller__=c.caller;return this.__native__apply(f,g)};O.call=function c(){this.__caller__=c.caller;return this.__native__call.__native__apply(this,arguments)}}b.prototype={__class__:null,__id__:null,parent:null,toString:function(){return this.__str__?
this.__str__():["[class ",this.__class__.className||"Anonymous","]"].join("")}};n.prototype={__addcol__:function(c,f){for(var g=0;g<f.length;g++)this.__add__.call(this,c,f[g][0],f[g][1],f[g][2],f[g][3])},__add__:function(c,f,g,e,q){if(d(f)==P&&f.length>0)for(var p=0;p<f.length;p++)this.__add__(c,f[p],g,e,q);else{e=e==undefined?d(g):e.typeId;if(e==undefined)throw Error("Unknown type "+e);if(e===s)g=new X(g);else if(e===x)g=new W(g);else if(e===M)g=new Boolean(g);else if(e===I)g=new String(g);else if(e===
J){var z=g.toString().replace(/\/\*.*\*\//,"").match(/function(\s+)?([a-zA-Z\$_0-9]+)?(\s+)?\(([a-zA-Z\$_0-9,\s]+)\)/),C,E,G,R;if(z&&z.length>1){z=z[4].replace(/\s+/g,"").split(",");C=Q.call(z,1).join(",");p=z[0];E=z[z.length-1];if(E=="__rest__"){G="__rest__";R=z.length-1}}else{C="";p="self"}G=["return function(",C,") {",G?["if(arguments.length>=",R,"){",G,"=[arguments[",R-1,"]];for(var _=",R,";_<arguments.length;_++)",G,"[_-",R-1,"]=arguments[_];}"].join(""):"",["return ",p,"[name].__func__(",p,
C&&[",",C].join(""),")"].join(""),"}"].join("");p=Function(p,"name",G)}else if(e===L)p={};else if(e===N)g=new Y;this[f]=p||g;this[f].flags=c;this[f].type=e;if(e===J){this[f].__func__=g;this[f].toString=j;this[f].returnType=q}else if(e===L)this[f].__class__=g}},__set__:function(){},__get__:function(){},__del__:function(c){this[c].flags&T&&delete this.__class__[c];delete this[c]},__call__:function(c){var f=Q.call(arguments,1);if(this[c].type===J)return this[c].__func__.apply(this[c],f)}};a.prototype=
{className:null,ancestors:null,members:null,instances:null,"new":null,toString:function(){return["class ",this.className||"Anonymous","(...)"].join("")},__init__:function(){}};v.$Unit=o;v.$Package=l;v.$Import=u;v.$ImportFrom=A;v.$Namespace=h;v.$buildClass=function(c,f,g){function e(){for(var p=new b,z=null,C=e.caller||e.__caller__,E=0;C;){if(C.__owner__){z=C.__owner__;break}C=C.caller;if(E>1E3){trace("Too much recursions in ",e.caller);break}E++}p.parent=z;z=q.instances.length;q.instances[z]=p;p.__id__=
z;p.__class__=q;w(p);if(p.__new__)var G=p.__new__.apply(p,arguments);return typeof G=="object"&&G!==null?G:p}var q=new a(c,f,g);H&&w(q);q["new"]=e;return q};v[V]={};v[V][S]="root";v.dict=function(c){for(var f={},g=0;g<c.length;g++)f[c[g][0]]=c[g][1];return f};v.Float=W;v.Int=X;v.Null=Y;v.Void=aa;v.Class=b;v.Type=k;v.XML||(v.XML=m);v.$window=t;v.$document=F;k.INT=X.typeId=s;k.FLOAT=W.typeId=x;k.BOOLEAN=Boolean.typeId=M;k.STRING=String.typeId=I;k.VOID=aa.typeId=9;k.NULL=Y.typeId=N;k.OBJECT=Object.typeId=
P;k.FUNCTION=Function.typeId=J;k.CLASS=b.typeId=L;k.XML=m.typeId=7;l("joo",function(c){c.Type=k;c.Import=u;c.ImportFrom=A;c.Package=l;c.Unit=o;c.Namespace=h;c.Group=i;c.Class=b;c.XML=m});U.when("contentloaded",function(){U.dispatch("initialize");H=true});window.attachEvent&&window.attachEvent("onbeforeunload",B)})();
$Unit(__PATH__,__FILE__,function(){$Package("geom",function(r){function l(b){return["(",b.join(", "),")"].join("")}function i(b,a){this.x=b||0;this.y=a||0}function w(b,a,d,j){this.__set(b,a,d,j)}function y(b,a,d,j,n,o){if(arguments.length)if(arguments.length===6){this.a=b;this.b=a;this.c=d;this.d=j;this.tx=n;this.ty=o}else throw Error("Not enough arguments");else this.identity()}i.prototype.vectorTo=function(b,a){return new i((b>this.x?1:-1)*(Math.max(this.x,b)-Math.min(this.x,b)),(a>this.y?1:-1)*
(Math.max(this.y,a)-Math.min(this.y,a)))};i.prototype.setPoint=function(b,a){this.x=b;this.y=a;return this};i.prototype.toString=function(){return l([this.x,this.y])};i["new"]=function(b,a){return new i(b,a)};w.prototype={__set:function(b,a,d,j){this.x=b;this.y=a;this.width=d;this.height=j;return this},isPointWithin:function(b,a){var d;if(arguments.length==1){d=b.x;a=b.y}else d=b;return d>this.x&&a>this.y&&d<this.x+this.width&&a<this.y+this.height},clone:function(){return new w(this.x,this.y,this.width,
this.height)},toString:function(){return l([this.x,this.y,this.width,this.height])},valueOf:function(){return[this.x,this.y,this.width,this.height]}};w["new"]=function(b,a,d,j){return new w(b,a,d,j)};y.prototype={identity:function(){this.a=1;this.c=this.b=0;this.d=1;this.ty=this.tx=0;return this},translate:function(b,a){this.tx=this.a*b+this.c*a;this.ty=this.b*b+this.d*a;return this},scale:function(b,a){this.a*=b;this.c*=b;this.b*=a;this.d*=a;return this},rotate:function(b){var a=Math.cos(b);b=Math.sin(b);
var d=this.b*a+this.d*b,j=this.a*-b+this.c*a,n=this.b*-b+this.d*a;this.a=this.a*a+this.c*b;this.b=d;this.c=j;this.d=n;return this},multiplyPoint:function(b){var a=this.clone().invert();b.x=b.x*a.a+b.y*a.c+a.tx;b.y=b.x*a.b+b.y*a.d+a.ty;return b},invert:function(){var b=1/(this.a*this.d-this.b*this.c),a=-this.b*b,d=b*(this.c*this.ty-this.d*this.tx),j=-this.c*b,n=this.a*b,o=b*(this.b*this.tx-this.a*this.ty);this.a=this.d*b;this.b=a;this.c=j;this.d=n;this.tx=d;this.ty=o;return this},clone:function(){return new y(this.a,
this.b,this.c,this.d,this.tx,this.ty)},toString:function(){return l(["a="+this.a,"b="+this.b,"c="+this.c,"d="+this.d,"tx="+this.tx,"ty="+this.ty])}};y["new"]=function(b,a,d,j,n,o){return new y(b,a,d,j,n,o)};r.Point=i;r.Rectangle=w;r.Matrix=y})});$Unit(__PATH__,__FILE__,function(){$Package("w3c",function(){})});
$Unit(__PATH__,__FILE__,function(r,l){$Package("browser",function(i){function w(o){for(var u=0;u<o.length;u++){var A=o[u].s,D=o[u].p;n=o[u].v||o[u].i;if(A){if(A.indexOf(o[u].u)!=-1)return o[u].i}else if(D)return o[u].i}}function y(o){var u=o.indexOf(n);if(u!=-1)return parseFloat(o.substring(u+n.length+1))}var b=navigator.appVersion,a=navigator.userAgent,d=navigator.platform,j=navigator.vendor,n;d=[{s:d,u:"Win",i:"Windows"},{s:d,u:"Mac",i:"Mac"},{s:a,u:"iPhone",i:"iPhone/iPod"},{s:d,u:"Linux",i:"Linux"}];
i.browser=w([{s:a,u:"Chrome",i:"Chrome"},{s:a,u:"OmniWeb",v:"OmniWeb/",i:"OmniWeb"},{s:j,u:"Apple",i:"Safari",v:"Version"},{p:window.opera,i:"Opera"},{s:j,u:"iCab",i:"iCab"},{s:j,u:"KDE",i:"Konqueror"},{s:a,u:"Firefox",i:"Firefox"},{s:j,u:"Camino",i:"Camino"},{s:a,u:"Netscape",i:"Netscape"},{s:a,u:"MSIE",i:"Explorer",v:"MSIE"},{s:a,u:"Gecko",i:"Mozilla",v:"rv"},{s:a,u:"Mozilla",i:"Netscape",v:"Mozilla"}])||"An unknown browser";i.version=y(a)||y(b)||"an unknown version";i.OS=w(d)||"an unknown OS";
i.isIE=!!(l.uniqueID&&l.expando&&i.browser==="Explorer");i.ie=i.isIE?i.version:0;i.isFirefox=i.browser==="Firefox";i.firefox=i.isFirefox?i.version:0;i.isOpera=i.browser==="Opera";i.opera=i.isOpera?i.version:0;i.isWebKit=i.browser==="Chrome"||i.browser==="Safari";i.webkit=i.isWebKit?1:0})});
$Unit(__PATH__,__FILE__,function(){$Package("geom",function(r){function l(b){return["(",b.join(", "),")"].join("")}function i(b,a){this.x=b||0;this.y=a||0}function w(b,a,d,j){this.__set(b,a,d,j)}function y(b,a,d,j,n,o){if(arguments.length)if(arguments.length===6){this.a=b;this.b=a;this.c=d;this.d=j;this.tx=n;this.ty=o}else throw Error("Not enough arguments");else this.identity()}i.prototype.vectorTo=function(b,a){return new i((b>this.x?1:-1)*(Math.max(this.x,b)-Math.min(this.x,b)),(a>this.y?1:-1)*
(Math.max(this.y,a)-Math.min(this.y,a)))};i.prototype.setPoint=function(b,a){this.x=b;this.y=a;return this};i.prototype.toString=function(){return l([this.x,this.y])};i["new"]=function(b,a){return new i(b,a)};w.prototype={__set:function(b,a,d,j){this.x=b;this.y=a;this.width=d;this.height=j;return this},isPointWithin:function(b,a){var d;if(arguments.length==1){d=b.x;a=b.y}else d=b;return d>this.x&&a>this.y&&d<this.x+this.width&&a<this.y+this.height},clone:function(){return new w(this.x,this.y,this.width,
this.height)},toString:function(){return l([this.x,this.y,this.width,this.height])},valueOf:function(){return[this.x,this.y,this.width,this.height]}};w["new"]=function(b,a,d,j){return new w(b,a,d,j)};y.prototype={identity:function(){this.a=1;this.c=this.b=0;this.d=1;this.ty=this.tx=0;return this},translate:function(b,a){this.tx=this.a*b+this.c*a;this.ty=this.b*b+this.d*a;return this},scale:function(b,a){this.a*=b;this.c*=b;this.b*=a;this.d*=a;return this},rotate:function(b){var a=Math.cos(b);b=Math.sin(b);
var d=this.b*a+this.d*b,j=this.a*-b+this.c*a,n=this.b*-b+this.d*a;this.a=this.a*a+this.c*b;this.b=d;this.c=j;this.d=n;return this},multiplyPoint:function(b){var a=this.clone().invert();b.x=b.x*a.a+b.y*a.c+a.tx;b.y=b.x*a.b+b.y*a.d+a.ty;return b},invert:function(){var b=1/(this.a*this.d-this.b*this.c),a=-this.b*b,d=b*(this.c*this.ty-this.d*this.tx),j=-this.c*b,n=this.a*b,o=b*(this.b*this.tx-this.a*this.ty);this.a=this.d*b;this.b=a;this.c=j;this.d=n;this.tx=d;this.ty=o;return this},clone:function(){return new y(this.a,
this.b,this.c,this.d,this.tx,this.ty)},toString:function(){return l(["a="+this.a,"b="+this.b,"c="+this.c,"d="+this.d,"tx="+this.tx,"ty="+this.ty])}};y["new"]=function(b,a,d,j,n,o){return new y(b,a,d,j,n,o)};r.Point=i;r.Rectangle=w;r.Matrix=y})});
