/*! JooScript basics v0.05 (20101206)
	- copyright 2009-2010, Evgeny Burzak <http://burzak.com/proj/jooscript-basics>
	- released under the MIT License <http://www.opensource.org/licenses/mit-license.php>
*/
var __PUBLIC__=0,__PRIVATE__=1,__STATIC__=2,__GLOBAL__=4,__FINAL__=8,__PROTECTED__=16,__FROZEN__=32,__INTERNAL__=49;__FILE__=__PATH__=__FUNC__=__CLASS__=__GROUP__=__LINE__="";
addDOMLoadEvent=function(){var q=[],k,i,u,w,c=function(){i=true;for(clearInterval(k);u=q.shift();)u()};window.__init__=c;return function(a){if(i)return a();if(!q[0]){!document.__w3c_fake&&document.addEventListener&&document.addEventListener("DOMContentLoaded",c,false);eval("/*@cc_on @*/");eval('/*@if(@_win32)document.write("<script id=__ie_onload defer src=//0></scr"+"ipt>");script=document.getElementById("__ie_onload");script.onreadystatechange=function(){if(this.readyState=="complete")__init__();};document.onreadystatechange=function(){if(document.readyState=="complete"){__init__();document.onreadystatechange=null;}}@*//*@end@*/');if(/WebKit/i.test(navigator.userAgent))k=
setInterval(function(){/loaded|complete/.test(document.readyState)&&c()},10);w=window.onload;window.onload=function(){c();w&&w()}}q.push(a)}}();
(function(){function q(){var a=this;this.useCapture=false;this.__class__=q;this.__id__=q.instances.length;q.instances.push(this);var f=q.members.__new__.__func__,h=q.members.when.__func__,m=q.members.dispatch.__func__,n=q.members.remove.__func__;f(a);this.when=function(s,z,B){return h(a,s,z,B,false)};this.once=function(s,z,B){return h(a,s,z,B,true)};this.dispatch=function(s,z){return m(a,s,z)};this.remove=function(s,z){return n(a,s,z)}}function k(a){a=(typeof a=="string"?a:a.type).toLowerCase();if(a==
w)return c;return a}function i(a,f){for(var h,m,n=0;n<f.length;n++)if(h=f[n])if(h.type==a){m=h.handler.call(h.context,{});if(h.fireOnce)f[n]=null;if(m)break}}var u=[];q.className="Event";q.instances=[];var w="DOMContentLoaded",c="contentloaded";q.members={__new__:{__func__:function(a){a.__listeners__=[]}},when:{__func__:function(a,f,h,m,n){var s;if(m==undefined||m==null){m=h;s=u}else s=a.__listeners__;evtype=k(f);evtype==c&&addDOMLoadEvent(function(){i(c,s)});s.push({type:evtype,handler:m,context:a,
fireOnce:n})}},dispatch:{__func__:function(a,f,h){f=k(f);i(f,h==undefined?u:a.__listeners__)}},remove:{__func__:function(a,f,h,m){if(m==undefined){m=h;a=u}else a=a.__listeners__;f=k(f);m=m;a=a;for(var n=0;n<a.length;n++)if(h=a[n])if(h.type==f&&h.handler===m)a[n]=null}}};q["new"]=function(){return new this};window.$Event=q})();
(function(){if(document.uniqueID&&document.expando){var q=function(i){this.code=this[i];this.message=i+": DOM Exception "+this.code},k=q.prototype=Error();k.INDEX_SIZE_ERR=1;k.DOMSTRING_SIZE_ERR=2;k.HIERARCHY_REQUEST_ERR=3;k.WRONG_DOCUMENT_ERR=4;k.INVALID_CHARACTER_ERR=5;k.NO_DATA_ALLOWED_ERR=6;k.NO_MODIFICATION_ALLOWED_ERR=7;k.NOT_FOUND_ERR=8;k.NOT_SUPPORTED_ERR=9;k.INUSE_ATTRIBUTE_ERR=10;k.INVALID_STATE_ERR=11;k.SYNTAX_ERR=12;k.INVALID_MODIFICATION_ERR=13;k.NAMESPACE_ERR=14;k.INVALID_ACCESS_ERR=
15;k.VALIDATION_ERR=16;k.TYPE_MISMATCH_ERR=17;window.DOMException||(window.DOMException=q)}})();
(function(){function q(j,l){for(var p in l)if(!(p in Object.prototype))if(p!="__w3c_fake"&&p!="toString"&&p!="__proto__"&&p!="valueOf")j[p]=l[p]}function k(){return{type:null,target:null,relatedTarget:null,currentTarget:null,offsetParent:null,offsetTop:null,offsetLeft:null,screenX:null,screenY:null,pageX:null,pageY:null,altKey:null,shiftKey:null,ctrlKey:null,metaKey:null,button:null,mouseButton:null,charCode:null,keyCode:null,IEvent:document.createEventObject(),preventDefault:function(){event.returnValue=
false},stopPropagation:function(){event.cancelBubble=true}}}function i(j,l,p){if(arguments.length<3)throw Error("Not enough arguments");if(typeof l!="function")throw Error("Event handler is not a function");j=""+j;p=!!p;var C="opener"in this;if(j in m)if(!(this.tagName&&this.tagName.toLowerCase()in h||this===document||C))return;var t=k();C=C&&(j in m||j in n)?f:this;var E=this,D="__ievent_hdlr_"+(p?"capture":"nocapture"),A=function(){t.type=event.type;t.target=event.srcElement;t.relatedTarget=event.fromElement||
event.toElement||null;t.currentTarget=E;t.offsetParent=event.srcElement&&event.srcElement.parentNode||null;t.offsetTop=event.offsetX;t.offsetLeft=event.offsetY;t.screenX=event.screenX;t.screenY=event.screenY;t.pageX=event.clientX+document.body.scrollLeft+document.documentElement.scrollLeft;t.pageY=event.clientY+document.body.scrollTop+document.documentElement.scrollTop;t.altKey=event.altKey;t.shiftKey=event.shiftKey;t.ctrlKey=event.ctrlKey;t.metaKey=false;t.keyCode=event.keyCode;t.charCode=j=="keypress"?
event.keyCode:0;if(event.button==1)t.button=0;else if(event.button==2)t.button=2;else if(event.button==4)t.button=1;t.mouseButton=event.button;l.call(E,t)},H=function(){var G=event,x={type:""};x.type=j;if(j==="DOMAttrModified"){x.ADDITION=2;x.MODIFICATION=1;x.REMOVAL=3;x.target=G.srcElement;x.relatedNode=null;x.attrChange=1;x.attrName=G.propertyName.split(".")[0];x.prevValue=null;x.newValue=x.target[x.attrName];if(x.attrName=="innerHTML"||x.attrName=="innerText"||typeof x.newValue=="function")return}l.call(E,
x)};l[D]=j.indexOf("DOM")===0?H:A;if(j==="DOMContentLoaded")addDOMLoadEvent(l[D]);else j==="DOMAttrModified"?C.attachEvent("onpropertychange",l[D]):C.attachEvent("on"+j,l[D])}function u(j,l,p){p="__ievent_hdlr_"+(p?"cap":"nocap");l[p]&&this.detachEvent("on"+j,l[p])}function w(j){return this.fireEvent("on"+j.type,j.IEvent)}function c(){for(var j=arguments,l,p=0;p<j.length;p++)if(j[p]){if(typeof j[p]=="string")l=document.getElementById(j[p]);else if(typeof j[p]=="object")l=j[p];if(!l.__w3c_fake){l.addEventListener=
i;l.removeEventListener=u;l.dispatchEvent=w;l.__w3c_fake=true}}}var a=window,f=a.document;if(f.uniqueID&&f.expando){if(!a.__w3c_fake){document.createElement("canvas");document.createStyleSheet().cssText="canvas{display:inline-block;overflow:hidden;width:300px;height:150px}";var h={textarea:true,input:true,select:true,body:true},m={keydown:"keydown",keyup:"keyup",keypress:"keypress"},n={mouseenter:"mouseenter",mouseleave:"mouseleave",mousemove:"mousemove",mouseup:"mouseup",mousedown:"mousedown",click:"click"},
s;document.__native__createElement=document.createElement;document.createElement=function(j){if(/^[a-z]+$/i.test(j))j=j.toUpperCase();j=document.__native__createElement(j);var l=window,p;p=j.tagName.toLowerCase();p=p.substr(0,1).toUpperCase()+p.substr(1);j=(l=l["HTML"+p+"Element"])&&l.__IElementConstructor?l.__IElementConstructor(j):j;c(j);s.__w3c_fake&&q(j,s.prototype);l&&l.__w3c_fake&&q(j,l.prototype);return j};document.createEvent=function(j){var l=k();if(j=="MouseEvents"||j=="MouseEvent")l.initMouseEvent=
function(p,C,t,E,D,A,H,G,x,v,aa,R,S,I,J){this.type=this.IEvent.type=p;this.bubbles=C;this.cancelable=t;this.view=E;this.detail=D;this.screenX=A;this.screenY=H;this.clientX=G;this.clientY=x;this.ctrlKey=v;this.altKey=aa;this.shiftKey=R;this.metaKey=S;this.button=I;this.relatedTarget=J};else if(j=="KeyboardEvent"||j=="KeyEvents")l.initKeyEvent=function(p,C,t,E,D,A,H,G,x,v){this.type=this.IEvent.type=p;this.bubbles=C;this.cancelable=t;this.view=E;this.ctrlKey=D;this.altKey=A;this.shiftKey=H;this.keyCode=
x;this.charCode=v};else l.initEvent=function(p,C,t){this.type=this.IEvent.type=p;this.bubbles=C;this.cancelable=t};return l};f.defaultView=a;a.getComputedStyle=function(j){return{getPropertyValue:function(l){return j.currentStyle[l]}}};c.all=function(){for(var j=f.all,l=0;l<j.length;l+=1)c(j[l])};a.w3c=c;for(var z=["HTMLElement"],B=0;B<z.length;B++)a[z[B]]||(a[z[B]]={prototype:{},__elementName:z[B],toString:function(){return"[object "+this.__elementName+"]"},__w3c_fake:true});s=a.HTMLElement}}else{a.w3c=
function(){};w3c.all=w3c}})();(function(){if(typeof console=="undefined")window.console={log:function(){for(var q=[],k=0;k<arguments.length;k++)q.push(arguments[k]);typeof alert=="undefined"?print.apply(null,q):alert(q.join(", "))},dir:function(){}};window.trace=function(){console&&console.log(["trace: ",Array.prototype.slice.call(arguments,0).join(" ")].join(""))}})();
(function(){function q(b){this.message=b}function k(b,e){var d=b.split(fa);d=p(d);e.call(d,d)}function i(b){this[T]=b}function u(b,e){for(var d in e)if(!(d in Object.prototype)&&!(d in Function.prototype)&&!(d in h.prototype)&&d!="__proto__"&&d!=T)b[d]=e[d]}function w(b){var e=b.__class__||b,d,g,r;if(e!=b)d=b;c(e);e.body.call(e.members,e);for(var o in e.members)if(!(o in z.prototype)){g=e.members[o];r=g.type;if(b===e){if(!(g.flags&U))continue}else if(g.flags&U)continue;if(r===K)if(g.flags&U)b[o]=
g.__func__;else{b[o]=g(b,o);b[o].__name__=o;b[o].__owner__=b;b[o].__func__=g.__func__;b[o].toString=g.toString}else b[o]=r===O?g:r===V?g.valueOf():r===I||r===J?g.valueOf():r===W?g.valueOf():r===X?null:g}d||e.__init__()}function c(b,e,d){e||(e=b);for(var g=e.ancestors,r=0;r<g.length;r++){if(g[r]==undefined)throw Error("Undefined ancestor in class "+b.className);g[r]!=b&&g[r]!=e&&c(b,g[r],d);g[r].body.call(b.members,b);if(g[r].className)b.ancestors[g[r].className]=g[r]}}function a(b){var e=0;b=b.caller||
b.__caller__;for(var d=null;b;){if(b.__owner__){d=b.__owner__;break}b=b.caller;if(e>1E3){trace("Too much recursions in ",b);break}e++}return d}function f(){var b=new h;u(b,this.prototype);if(!this.className){var e=this.toString().match(/function(\s+)?([a-zA-Z\$_0-9]+)?/);this.className=e&&e[2]||"Anonymous"}b.__class__=this;if(!this.instances)this.instances=[];b.__id__=this.instances.length;b.parent=a(f);this.instances.push(b);this.prototype.constructor.apply(b,arguments);return b}function h(){}function m(b,
e,d){this.instances=[];this.className=b;this.ancestors=[];if(e&&e.length>0)for(b=0;b<e.length;b++)this.ancestors[b]=e[b];this.body=d;this.members=new z;var g=this;ba.once("initialize",function(){w(g)});ga[ga.length]=this}function n(b){switch(typeof b){case "string":return V;case "function":return b instanceof m?O:K;case "boolean":return W;case "object":return ca;case "number":return b.toString().indexOf(".")>-1?J:I;default:return X}}function s(){return"function(){/*stub*/}"}function z(){}function B(b,
e,d){var g=new E;g.__path__=b;g.__file__=e;d.call(g,g,aa,v)}function j(b){var e,d,g,r,o=P.call(arguments,1);if(typeof b=="string")b=v;for(var y=0;y<o.length;y+=1){e=o[y];d=e.split(fa);g=ia.call(d);d=g=="*"?P.call(d,0,d.length-1):d;try{r=p(d)}catch(F){throw new q("Symbol "+F+" not found in "+e);}if(g==="*")u(b,r);else b[g]=r}return b}function l(){}function p(b,e){var d=G[da],g=d,r,o;if(b.length==1&&!b[0])return g;for(o=0;o<b.length;o++){r=b[o];if(!d[T])throw"Token '"+r+"' is not group token";g=d[r];
if(typeof g=="undefined")if(e)throw r+" not found";else g=d=d[r]=new i(r);else if(o==b.length-1)break;else{d=g;g=d[r]}}return g}function C(b,e,d){b={};d&&u(b,d);u(b,e);return b}function t(){}function E(b){return{__url__:b}}function D(){P.call(arguments,0).join("")}function A(){throw Error("Type is not constructor");}function H(){window.detachEvent("onbeforeunload",H)}var G=window,x=document,v=G,aa=x,R=false,S=typeof $joo_compat!="undefined"&&$joo_compat||true,I=0,J=1,V=2,W=3,ca=4,K=5,O=6,X=8,U=__STATIC__,
Y=function(b){b=new Number(b);b.typeId=J;return b},Z=function(b){b=new Number(b);b.typeId=I;return b},$=function(){return null},ea=function(){},ha=function(b){return Object(b)},da="$groups",T="__groupToken__",fa=".",P=Array.prototype.slice,ia=function(){return this[this.length-1]},ba=$Event["new"]();q.prototype=Error();i.prototype={addClass:function(b,e){this[e.className]=e}};var ga=[];Function.prototype["new"]=f;if(window.Touch){var L=Function.prototype;L.__native__apply=L.apply;L.__native__call=
L.call;L.apply=function b(e,d){this.__caller__=b.caller;return this.__native__apply(e,d)};L.call=function b(){this.__caller__=b.caller;return this.__native__call.__native__apply(this,arguments)}}h.prototype={__class__:null,__id__:null,parent:null,toString:function(){return this.__str__?this.__str__():["[class ",this.__class__&&this.__class__.className||"Anonymous","]"].join("")}};z.prototype={__addcol__:function(b,e){for(var d=0;d<e.length;d++)this.__add__.call(this,b,e[d][0],e[d][1],e[d][2],e[d][3])},
__add__:function(b,e,d,g,r){if(n(e)==ca&&e.length>0)for(var o=0;o<e.length;o++)this.__add__(b,e[o],d,g,r);else{g=g==undefined?n(d):g.typeId;if(g==undefined)throw Error("Unknown type "+g);if(g===I)d=new Z(d);else if(g===J)d=new Y(d);else if(g===W)d=new Boolean(d);else if(g===V)d=new String(d);else if(g===K){var y=d.toString().replace(/\/\*.*\*\//,"").match(/function(\s+)?([a-zA-Z\$_0-9]+)?(\s+)?\(([a-zA-Z\$_0-9,\s]+)\)/),F,M,N,Q;if(y&&y.length>1){y=y[4].replace(/\s+/g,"").split(",");F=P.call(y,1).join(",");
o=y[0];M=y[y.length-1];if(M=="__rest__"){N="__rest__";Q=y.length-1}}else{F="";o="self"}N=["return function(",F,") {",N?["if(arguments.length>=",Q,"){",N,"=[arguments[",Q-1,"]];for(var _=",Q,";_<arguments.length;_++)",N,"[_-",Q-1,"]=arguments[_];}"].join(""):"",["return ",o,"[name].__func__(",o,F&&[",",F].join(""),")"].join(""),"}"].join("");o=Function(o,"name",N)}else if(g===O)o={};else if(g===X)d=new $;this[e]=o||d;this[e].flags=b;this[e].type=g;if(g===K){this[e].__func__=d;this[e].toString=s;this[e].returnType=
r}else if(g===O)this[e].__class__=d}},__set__:function(){},__get__:function(){},__del__:function(b){this[b].flags&U&&delete this.__class__[b];delete this[b]},__call__:function(b){var e=P.call(arguments,1);if(this[b].type===K)return this[b].__func__.apply(this[b],e)}};m.prototype={className:null,ancestors:null,members:null,instances:null,"new":null,role:null,as:function(b){this.role=b;return this},toString:function(){return["class ",this.className||"Anonymous","(...)"].join("")},__init__:function(){}};
v.$Unit=B;v.$Package=k;v.$Import=j;v.$ImportFrom=l;v.$Namespace=E;v.$buildClass=function(b,e,d,g){function r(){var y=new h;y.parent=a(r);var F=o.instances.length;o.instances[F]=y;y.__id__=F;y.__class__=o;w(y);if(y.__new__)var M=y.__new__.apply(y,arguments);return typeof M=="object"&&M!==null?M:y}var o=new m(b,e,d);R&&w(o);g&&o.as(g);o["new"]=r;return o};v[da]={};v[da][T]="root";v.dict=function(b){for(var e={},d=0;d<b.length;d++)e[b[d][0]]=b[d][1];return e};if(!S){v.Stem=ha;v.Float=Y;v.Int=Z;v.Vector=
t;v.Null=$;v.Void=ea;v.Class=h;v.Type=A}v.XML||S||(v.XML=D);v.$window=G;v.$document=x;A.INT=Z.typeId=I;A.FLOAT=Y.typeId=J;A.BOOLEAN=Boolean.typeId=W;A.STRING=String.typeId=V;A.VOID=ea.typeId=9;A.NULL=$.typeId=X;A.OBJECT=Object.typeId=ca;A.FUNCTION=Function.typeId=K;A.CLASS=h.typeId=O;A.XML=D.typeId=7;k("joo",function(b){b.Stem=ha;b.Float=Y;b.Int=Z;b.Null=$;b.Void=ea;b.Vector=t;b.Type=A;b.Role=C;b.Import=j;b.ImportFrom=l;b.Package=k;b.Unit=B;b.Namespace=E;b.Group=i;b.Class=h;b.XML=D});ba.once("contentloaded",
function(){ba.dispatch("initialize");R=true});window.attachEvent&&window.attachEvent("onbeforeunload",H)})();
$Unit(__PATH__,__FILE__,function(){$Package("geom",function(q){function k(c){return["(",c.join(", "),")"].join("")}function i(c,a){this.x=c||0;this.y=a||0}function u(c,a,f,h){this.__set(c,a,f,h)}function w(c,a,f,h,m,n){if(arguments.length)if(arguments.length===6){this.a=c;this.b=a;this.c=f;this.d=h;this.tx=m;this.ty=n}else throw Error("Not enough arguments");else this.identity()}i.prototype.vectorTo=function(c,a){return new i((c>this.x?1:-1)*(Math.max(this.x,c)-Math.min(this.x,c)),(a>this.y?1:-1)*
(Math.max(this.y,a)-Math.min(this.y,a)))};i.prototype.setPoint=function(c,a){this.x=c;this.y=a;return this};i.prototype.toString=function(){return k([this.x,this.y])};i["new"]=function(c,a){return new i(c,a)};u.prototype={__set:function(c,a,f,h){this.x=c;this.y=a;this.width=f;this.height=h;return this},isPointWithin:function(c,a){var f;if(arguments.length==1){f=c.x;a=c.y}else f=c;return f>this.x&&a>this.y&&f<this.x+this.width&&a<this.y+this.height},clone:function(){return new u(this.x,this.y,this.width,
this.height)},toString:function(){return k([this.x,this.y,this.width,this.height])},valueOf:function(){return[this.x,this.y,this.width,this.height]}};u["new"]=function(c,a,f,h){return new u(c,a,f,h)};w.prototype={identity:function(){this.a=1;this.c=this.b=0;this.d=1;this.ty=this.tx=0;return this},translate:function(c,a){this.tx=this.a*c+this.c*a;this.ty=this.b*c+this.d*a;return this},scale:function(c,a){this.a*=c;this.c*=c;this.b*=a;this.d*=a;return this},rotate:function(c){var a=Math.cos(c);c=Math.sin(c);
var f=this.b*a+this.d*c,h=this.a*-c+this.c*a,m=this.b*-c+this.d*a;this.a=this.a*a+this.c*c;this.b=f;this.c=h;this.d=m;return this},multiplyPoint:function(c){var a=this.clone().invert();c.x=c.x*a.a+c.y*a.c+a.tx;c.y=c.x*a.b+c.y*a.d+a.ty;return c},invert:function(){var c=1/(this.a*this.d-this.b*this.c),a=-this.b*c,f=c*(this.c*this.ty-this.d*this.tx),h=-this.c*c,m=this.a*c,n=c*(this.b*this.tx-this.a*this.ty);this.a=this.d*c;this.b=a;this.c=h;this.d=m;this.tx=f;this.ty=n;return this},clone:function(){return new w(this.a,
this.b,this.c,this.d,this.tx,this.ty)},toString:function(){return k(["a="+this.a,"b="+this.b,"c="+this.c,"d="+this.d,"tx="+this.tx,"ty="+this.ty])}};w["new"]=function(c,a,f,h,m,n){return new w(c,a,f,h,m,n)};q.Point=i;q.Rectangle=u;q.Matrix=w})});$Unit(__PATH__,__FILE__,function(){$Package("w3c",function(){})});
$Unit(__PATH__,__FILE__,function(q,k){$Package("browser",function(i){function u(n){for(var s=0;s<n.length;s++){var z=n[s].s,B=n[s].p;m=n[s].v||n[s].i;if(z){if(z.indexOf(n[s].u)!=-1)return n[s].i}else if(B)return n[s].i}}function w(n){var s=n.indexOf(m);if(s!=-1)return parseFloat(n.substring(s+m.length+1))}var c=navigator.appVersion,a=navigator.userAgent,f=navigator.platform,h=navigator.vendor,m;f=[{s:f,u:"Win",i:"Windows"},{s:f,u:"Mac",i:"Mac"},{s:a,u:"iPhone",i:"iPhone/iPod"},{s:f,u:"Linux",i:"Linux"}];
i.browser=u([{s:a,u:"Chrome",i:"Chrome"},{s:a,u:"OmniWeb",v:"OmniWeb/",i:"OmniWeb"},{s:h,u:"Apple",i:"Safari",v:"Version"},{p:window.opera,i:"Opera"},{s:h,u:"iCab",i:"iCab"},{s:h,u:"KDE",i:"Konqueror"},{s:a,u:"Firefox",i:"Firefox"},{s:h,u:"Camino",i:"Camino"},{s:a,u:"Netscape",i:"Netscape"},{s:a,u:"MSIE",i:"Explorer",v:"MSIE"},{s:a,u:"Gecko",i:"Mozilla",v:"rv"},{s:a,u:"Mozilla",i:"Netscape",v:"Mozilla"}])||"An unknown browser";i.version=w(a)||w(c)||"an unknown version";i.OS=u(f)||"an unknown OS";
i.isIE=!!(k.uniqueID&&k.expando&&i.browser==="Explorer");i.ie=i.isIE?i.version:0;i.isFirefox=i.browser==="Firefox";i.firefox=i.isFirefox?i.version:0;i.isOpera=i.browser==="Opera";i.opera=i.isOpera?i.version:0;i.isWebKit=i.browser==="Chrome"||i.browser==="Safari";i.webkit=i.isWebKit?1:0})});
$Unit(__PATH__,__FILE__,function(){$Package("geom",function(q){function k(c){return["(",c.join(", "),")"].join("")}function i(c,a){this.x=c||0;this.y=a||0}function u(c,a,f,h){this.__set(c,a,f,h)}function w(c,a,f,h,m,n){if(arguments.length)if(arguments.length===6){this.a=c;this.b=a;this.c=f;this.d=h;this.tx=m;this.ty=n}else throw Error("Not enough arguments");else this.identity()}i.prototype.vectorTo=function(c,a){return new i((c>this.x?1:-1)*(Math.max(this.x,c)-Math.min(this.x,c)),(a>this.y?1:-1)*
(Math.max(this.y,a)-Math.min(this.y,a)))};i.prototype.setPoint=function(c,a){this.x=c;this.y=a;return this};i.prototype.toString=function(){return k([this.x,this.y])};i["new"]=function(c,a){return new i(c,a)};u.prototype={__set:function(c,a,f,h){this.x=c;this.y=a;this.width=f;this.height=h;return this},isPointWithin:function(c,a){var f;if(arguments.length==1){f=c.x;a=c.y}else f=c;return f>this.x&&a>this.y&&f<this.x+this.width&&a<this.y+this.height},clone:function(){return new u(this.x,this.y,this.width,
this.height)},toString:function(){return k([this.x,this.y,this.width,this.height])},valueOf:function(){return[this.x,this.y,this.width,this.height]}};u["new"]=function(c,a,f,h){return new u(c,a,f,h)};w.prototype={identity:function(){this.a=1;this.c=this.b=0;this.d=1;this.ty=this.tx=0;return this},translate:function(c,a){this.tx=this.a*c+this.c*a;this.ty=this.b*c+this.d*a;return this},scale:function(c,a){this.a*=c;this.c*=c;this.b*=a;this.d*=a;return this},rotate:function(c){var a=Math.cos(c);c=Math.sin(c);
var f=this.b*a+this.d*c,h=this.a*-c+this.c*a,m=this.b*-c+this.d*a;this.a=this.a*a+this.c*c;this.b=f;this.c=h;this.d=m;return this},multiplyPoint:function(c){var a=this.clone().invert();c.x=c.x*a.a+c.y*a.c+a.tx;c.y=c.x*a.b+c.y*a.d+a.ty;return c},invert:function(){var c=1/(this.a*this.d-this.b*this.c),a=-this.b*c,f=c*(this.c*this.ty-this.d*this.tx),h=-this.c*c,m=this.a*c,n=c*(this.b*this.tx-this.a*this.ty);this.a=this.d*c;this.b=a;this.c=h;this.d=m;this.tx=f;this.ty=n;return this},clone:function(){return new w(this.a,
this.b,this.c,this.d,this.tx,this.ty)},toString:function(){return k(["a="+this.a,"b="+this.b,"c="+this.c,"d="+this.d,"tx="+this.tx,"ty="+this.ty])}};w["new"]=function(c,a,f,h,m,n){return new w(c,a,f,h,m,n)};q.Point=i;q.Rectangle=u;q.Matrix=w})});
