/*! Web-Forkers v0.01(preview) (20101225)
	- copyright 2009-2010, Evgeny Burzak <http://code.google.com/p/web-forkers/>
	- released under the MIT License <http://www.opensource.org/licenses/mit-license.php>
*/
var Forker=function(){function t(a){return a.replace(/[%&=\+]/g,function(k){if(k=="%")return"%25";else if(k=="&")return"%26";else if(k=="=")return"%3D";else if(k=="+")return"%2B"})}function u(a){function k(){window.detachEvent("onbeforeunload",k);for(var f=0;f<m._forkers.length;f++)m._forkers[f]&&m._forkers[f].terminate()}var i=++v;a=a.replace(/\.js$/,".swf");var e=document.createElement("div");e.style.position="absolute";e.style.right=e.style.top="0px";a=['<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000"  width="',
w,'" height="',x,'" id="__forker_',i,'" style="position:absolute;right:0px;top:0px;"><param name="allowScriptAccess" value="always"><param name="movie" value="',a,'"><param name="quality" value="low"><param name="menu" value="false"><param name="wmode" value="transparent"><param name="FlashVars" value="m="></object><script id=__fscmd_hlr_',i," event=FSCommand(cmd,args) for=__forker_",i,">if(Forker){Forker._forkers[",i,"]._args=args;Forker._forkers[",i,"]._fscmd(cmd);}<\/script>"].join("");e.innerHTML=
a;document.body.appendChild(e);a={};a._flashObject=e.firstChild;a._data=null;a._args=null;a._listeners=[];a.blobData=false;a.rawData=false;var g={};a._fscmd=function(f){g.type=f;if(this.blobData){var c=[],b,d,l,j,o=Number(f);if(o){for(var h=0;h<o;h++){b=this._args.charCodeAt(h);d=this._args.charCodeAt(h+1)^b&2;l=this._args.charCodeAt(h+2)^b&4;j=this._args.charCodeAt(h+3)^b&8;b=this._args.charCodeAt(h+4)^b&16;c[h]=[d,l,j,b].join("")}g.data=c.join("")}}else g.data=this._args;if(f=="error")this.onerror&&
this.onerror(g);else this.onmessage&&this.onmessage(g);for(h=0;h<this._listeners.length;h++)this._listeners[h].type==f&&this._listeners[h].fun(g)};a.onmessage=function(){};a.onerror=function(){};a.terminate=function(){if(this._flashObject){e.removeChild(this._flashObject);e.removeChild(e.firstChild);document.body.removeChild(e);this._flashObject=null}};var n=0;a.postMessage=function(f){f=["b=",this.blobData?"1":"0","&r=",this.rawData?"1":"0","&i=",n++,"&m=",this.rawData?f:this.blobData?this.blob2str(f):
t(f)].join("");this._flashObject.FlashVars=f};a.blob2str=function(f){for(var c=[],b=0;b<256;b++)switch(b){case 0:case 37:case 38:case 43:case 61:c[b]=1;break;default:c[b]=0}for(b=0;b<imageData.data.length;b++){var d=imageData.data[b],l=d>>24&255,j=d>>16&255,o=d>>8&255;d=d&255;var h=c[l]<<1,p=c[j]<<2,q=c[o]<<3,r=c[d]<<4;strBuf[strBuf.length]=String.fromCharCode(h+p+q+r+1,l^h,j^p,o^q,d^r)}return f};a.addEventListener=function(f,c,b){if(b==undefined)throw Error("use_capture is undefined");this._listeners.push({type:f,
fun:c})};m._forkers[i]=a;window.attachEvent("onbeforeunload",k);return a}function y(a){function k(){for(var c=Array.prototype.slice.call(arguments,0),b=0;b<c.length;b++){var d=new XMLHttpRequest;d.open("GET",c[b],false);d.send(null);if(d.status==0||d.status==200){d=Function("self","importScripts","window","document",d.responseText);try{d.call(g,g,k,null,null)}catch(l){i(e,"error",{message:l.message,lineno:0})}}else i(e,"error",{message:"Error loading script",lineno:0})}}function i(c,b,d){var l=c.__listeners__,
j;j={type:b};if(b=="message")j.data=d;else if(b=="error"){j.message=d.message;j.lineno=d.lineno||0}typeof c["on"+b]=="function"&&c["on"+b](j);for(c=0;c<l.length;c++){d=l[c];d.type==b&&d.handler&&d.handler(j)}}var e={},g={},n=[];g.addEventListener=function(c,b){g.__listeners__.push({type:c,handler:b})};g.postMessage=function(c){i(e,"message",c)};g.importScripts=k;g.__listeners__=[];g.navigator=window.navigator;e.__listeners__=[];var f;f=setInterval(function(){if(a){k(a);a=null}if(n.length)try{i(g,
"message",n.shift())}catch(c){i(g,"error",c)}},1E3);e.onmessage=function(){};e.onerror=function(){};e.terminate=function(){e.__listeners__=null;e=g=n=g.__listeners__=null;clearInterval(f)};e.postMessage=function(c){n.push(c)};e.addEventListener=function(c,b,d){if(d==undefined)throw Error("use_capture is undefined");e.__listeners__.push({type:c,handler:handler})};return e}var s=document.uniqueID&&document.expando,m=function(){return typeof Worker!="undefined"?function(a){return new Worker(a)}:s?function(a){return u(a)}:
function(a){return y(a)}}();if(s){var v=0,w=1,x=1;m._forkers=[]}return m}();
