/*! Web-Forkers v0.02(preview) (20110102)
	- copyright 2009-2011, Evgeny Burzak <http://code.google.com/p/web-forkers/>
	- released under the MIT License <http://www.opensource.org/licenses/mit-license.php>
*/
if(typeof Forker=="undefined")var Forker=function(){function i(a){return a.replace(/[%&=\+]/g,function(j){if(j=="%")return"%25";else if(j=="&")return"%26";else if(j=="=")return"%3D";else if(j=="+")return"%2B"})}function k(a){function j(){window.detachEvent("onbeforeunload",j);for(var f=0;f<h._forkers.length;f++)h._forkers[f]&&h._forkers[f].terminate()}var m=++o;a=a.replace(/\.js$/,".swf");var e=document.createElement("div");e.style.position="absolute";e.style.right=e.style.top="0px";a=['<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000"  width="',
s,'" height="',t,'" id="__forker_',m,'" style="position:absolute;right:0px;top:0px;"><param name="allowScriptAccess" value="always"><param name="movie" value="',a,'"><param name="quality" value="low"><param name="menu" value="false"><param name="wmode" value="transparent"><param name="FlashVars" value="m="></object><script id=__fscmd_hlr_',m," event=FSCommand(cmd,args) for=__forker_",m,">if(Forker){Forker._forkers[",m,"]._args=args;Forker._forkers[",m,"]._fscmd(cmd);}<\/script>"].join("");e.innerHTML=
a;document.body.appendChild(e);a={};a._flashObject=e.firstChild;a._data=null;a._args=null;a._listeners=[];a.blobData=false;a.rawData=false;var g={};a._fscmd=function(f){g.type=f;if(this.blobData){var c=[],b,d,r,p,v=Number(f);if(v){for(var l=0;l<v;l++){b=this._args.charCodeAt(l);d=this._args.charCodeAt(l+1)^b&2;r=this._args.charCodeAt(l+2)^b&4;p=this._args.charCodeAt(l+3)^b&8;b=this._args.charCodeAt(l+4)^b&16;c[l]=[d,r,p,b].join("")}g.data=c.join("")}}else g.data=this._args;if(f=="error")this.onerror&&
this.onerror(g);else this.onmessage&&this.onmessage(g);for(l=0;l<this._listeners.length;l++)this._listeners[l].type==f&&this._listeners[l].fun(g)};a.onmessage=function(){};a.onerror=function(){};a.terminate=function(){if(this._flashObject){e.removeChild(this._flashObject);e.removeChild(e.firstChild);document.body.removeChild(e);this._flashObject=null}};var u=0;a.postMessage=function(f){if(typeof f==="object")throw Error("NOT_SUPPORTED_ERR");f=["b=",this.blobData?"1":"0","&r=",this.rawData?"1":"0",
"&i=",u++,"&m=",this.rawData?f:this.blobData?this.blob2str(f):i(f)].join("");this._flashObject.FlashVars=f};a.blob2str=function(f){for(var c=[],b=0;b<256;b++)switch(b){case 0:case 37:case 38:case 43:case 61:c[b]=1;break;default:c[b]=0}for(b=0;b<imageData.data.length;b++){var d=imageData.data[b],r=d>>24&255,p=d>>16&255,v=d>>8&255;d=d&255;var l=c[r]<<1,w=c[p]<<2,x=c[v]<<3,y=c[d]<<4;strBuf[strBuf.length]=String.fromCharCode(l+w+x+y+1,r^l,p^w,v^x,d^y)}return f};a.addEventListener=function(f,c,b){if(b==
undefined)throw Error("use_capture is undefined");this._listeners.push({type:f,fun:c})};h._forkers[m]=a;window.attachEvent("onbeforeunload",j);return a}function q(a){function j(){for(var c=Array.prototype.slice.call(arguments,0),b=0;b<c.length;b++){var d=new XMLHttpRequest;d.open("GET",c[b],false);d.send(null);if(d.status==0||d.status==200){d=Function("self","importScripts","window","document",d.responseText);try{d.call(g,g,j,null,null)}catch(r){m(e,"error",{message:r.message,lineno:0})}}else m(e,
"error",{message:"Error loading script",lineno:0})}}function m(c,b,d){var r=c.__listeners__,p;p={type:b};if(b=="message")p.data=d;else if(b=="error"){p.message=d.message;p.lineno=d.lineno||0}typeof c["on"+b]=="function"&&c["on"+b](p);for(c=0;c<r.length;c++){d=r[c];d.type==b&&d.handler&&d.handler(p)}}var e={},g={},u=[];g.addEventListener=function(c,b){g.__listeners__.push({type:c,handler:b})};g.postMessage=function(c){m(e,"message",c)};g.importScripts=j;g.__listeners__=[];g.navigator=window.navigator;
e.__listeners__=[];var f;f=setInterval(function(){if(a){j(a);a=null}if(u.length)try{m(g,"message",u.shift())}catch(c){m(g,"error",c)}},1E3);e.onmessage=function(){};e.onerror=function(){};e.terminate=function(){e.__listeners__=null;e=g=u=g.__listeners__=null;clearInterval(f)};e.postMessage=function(c){u.push(c)};e.addEventListener=function(c,b,d){if(d==undefined)throw Error("use_capture is undefined");e.__listeners__.push({type:c,handler:handler})};return e}var n=typeof document!=="undefined"&&document.uniqueID&&
document.expando,h=function(){return typeof Worker!="undefined"?function(a){return new Worker(a)}:n?function(a){return k(a)}:function(a){return q(a)}}();if(n){var o=0,s=1,t=1;h._forkers=[]}return h}();function JSON2ImageData(i){var k=i.indexOf(";"),q=i.substring(0,k).split(","),n=parseInt(q[0]);q=parseInt(q[1]);var h=[];i=i.substr(k+1);for(k=0;k<n*q;k++){var o=k*5,s=i.charCodeAt(o),t=i.charCodeAt(o+1)^s&2,a=i.charCodeAt(o+2)^s&4,j=i.charCodeAt(o+3)^s&8;o=i.charCodeAt(o+4)^s&16;h[k]=(t<<24)+(a<<16)+(j<<8)+o}return{width:n,height:q,data:h}}
function ImageData2JSON(i){for(var k=[],q=[],n=0;n<256;n++)switch(n){case 0:case 37:case 38:case 43:case 61:k[n]=1;break;default:k[n]=0}for(n=0;n<i.data.length;n++){var h=i.data[n],o=h>>24&255,s=h>>16&255,t=h>>8&255;h=h&255;var a=k[o]<<1,j=k[s]<<2,m=k[t]<<3,e=k[h]<<4;q[q.length]=String.fromCharCode(a+j+m+e+1,o^a,s^j,t^m,h^e)}return[i.width,",",i.height,";",q.join("")].join("")};
